### ISSUE TITLE
Undefined symbols  with enable-cross-module-inlining  and Fiber.reset

### ISSUE THREAD

**Issue by changloong** [ldc-developers/ldc#1903] opened 2016-11-28 16:36 UTC
`test.d` example with 1.1.0-beta5 MacOSX
```d
import core.thread;

void main(){
        void onDev(){
                Fiber.yield;
        }
        auto fiber = new Fiber(&onDev);
        fiber.reset;
}
```

```sh
ldc2 test.d -enable-cross-module-inlining -O
Undefined symbols for architecture x86_64:
  "__D4core6thread5Fiber5resetMFNbZ9__requireMFNbZv", referenced from:
      __Dmain in test.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: /usr/bin/gcc failed with status: 1
```

**Comment by kinke** [comment] 2016-11-28 17:05
An exact duplicate of https://github.com/ldc-developers/ldc/issues/1727.

**Closed by kinke** 2016-11-28 17:05 UTC
