### ISSUE TITLE
LDC generates crashing DMD executable for continuous-integration/travis-ci

### ISSUE THREAD

**Issue by WalterBright** [ldc-developers/ldc#1850] opened 2016-10-21 23:58 UTC
Description here: https://github.com/dlang/dmd/pull/6208

LDC appears to be generating bad fixup relocations. This is a blocker for dmd development.

**Comment by kinke** [comment] 2016-10-22 00:04
Thx; this has got to be a duplicate of #1829.

**Comment by kinke** [comment] 2017-04-18 23:39
Closing this duplicate.

**Closed by kinke** 2017-04-18 23:39 UTC
