### ISSUE TITLE
testsuite triggers DIVariable::getPieceSize() assertion 

### ISSUE THREAD

**Issue by Trass3r** [ldc-developers/ldc#706] opened 2014-09-08 20:19 UTC
```
llvm/lib/IR/DebugInfo.cpp:164: uint64_t llvm::DIVariable::getPieceSize() const: Assertion `isVariablePiece()' failed.
ldc2            0x0000000001263e65 llvm::sys::PrintStackTrace(_IO_FILE*) + 37
ldc2            0x00000000012647db
libpthread.so.0 0x00002b651c623340
libc.so.6       0x00002b651d4a4bb9 gsignal + 57
libc.so.6       0x00002b651d4a7fc8 abort + 328
libc.so.6       0x00002b651d49da76
libc.so.6       0x00002b651d49db22
ldc2            0x000000000115eff5
ldc2            0x0000000000b454ed llvm::DwarfUnit::addComplexAddress(llvm::DbgVariable const&, llvm::DIE&, llvm::dwarf::Attribute, llvm::MachineLocation const&) + 413
ldc2            0x0000000000b452c0 llvm::DwarfUnit::addVariableAddress(llvm::DbgVariable const&, llvm::DIE&, llvm::MachineLocation) + 96
ldc2            0x0000000000b4bd48 llvm::DwarfUnit::constructVariableDIEImpl(llvm::DbgVariable const&, bool) + 840
ldc2            0x0000000000b4b9e2 llvm::DwarfUnit::constructVariableDIE(llvm::DbgVariable&, bool) + 18
ldc2            0x0000000000b27360 llvm::DwarfDebug::createScopeChildrenDIE(llvm::DwarfCompileUnit&, llvm::LexicalScope*, llvm::SmallVectorImpl<std::unique_ptr<llvm::DIE, std::default_delete<llvm::DIE> > >&, unsigned int*) + 496
ldc2            0x0000000000b27b67 llvm::DwarfDebug::createAndAddScopeChildren(llvm::DwarfCompileUnit&, llvm::LexicalScope*, llvm::DIE&) + 55
ldc2            0x0000000000b2848a llvm::DwarfDebug::constructSubprogramScopeDIE(llvm::DwarfCompileUnit&, llvm::LexicalScope*) + 986
ldc2            0x0000000000b32963 llvm::DwarfDebug::endFunction(llvm::MachineFunction const*) + 1139
ldc2            0x0000000000b1558e llvm::AsmPrinter::EmitFunctionBody() + 5166
ldc2            0x0000000000880a95
ldc2            0x0000000000bb2c2c llvm::MachineFunctionPass::runOnFunction(llvm::Function&) + 124
ldc2            0x00000000011f95bb llvm::FPPassManager::runOnFunction(llvm::Function&) + 539
ldc2            0x00000000011f982b llvm::FPPassManager::runOnModule(llvm::Module&) + 43
ldc2            0x00000000011f9da7 llvm::legacy::PassManagerImpl::run(llvm::Module&) + 967
ldc2            0x000000000058881d
ldc2            0x000000000058837c writeModule(llvm::Module*, std::string) + 1756
```
Seems to happen with tests link11931, opover2, testcontracts, test10942
llvm trunk, Release+Asserts+DebugInfo
Can anybody reproduce that?

**Comment by redstar** [comment] 2016-01-30 19:56
The problem is fixed in master (a long time ago). The problem was incorrect generation of debug information.

**Closed by redstar** 2016-01-30 19:56 UTC
