### ISSUE TITLE
Windows: ldmd2 makes x64<->x86 cross compilation in a VS environment difficult

### ISSUE THREAD

**Issue by rainers** [ldc-developers/ldc#3340] opened 2020-02-25 16:46 UTC
It's been really a pain and I ultimately failed when trying to replace dmd with ldmd2 while setting up CIs for dmd and the installers:

```
C:\tmp\d>"c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\vc\Auxiliary\Build\vcvarsall.bat" x86
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.4.4
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86'

C:\tmp\d>c:\d\ldc2-1.20.0-windows-multilib\bin\ldmd2.exe args.d
libcmt.lib(chkstk.obj) : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64'
Error: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x86\link.exe failed with status: 1112
```

If a VS environment is setup for one architecture (x64/x86) it is difficult to build tools for another platform or even the default architecture (when no -m argument is given), because the LIB environment variable is passed through unmodified to the linker, causing missing libraries or mismatched architecture. See for example the numerous attempts in https://github.com/dlang/dmd/pull/10814 .

Setting LDC_VSDIR and resetting VSINSTALLDIR is often not a solution because tools automatically invoked might need an unmodified environment.

dmd doesn't have this issue, it always prepends the needed library paths to the LIB variable or passes them directly via /LIBPATH to the linker. In order to work as a drop-in replacement ldmd2 should do this, too.

**Comment by kinke** [comment] 2020-02-25 17:16
> If a VS environment is setup for one architecture (x64/x86) it is difficult to build tools for another platform

Yeah well, that setup is clearly suboptimal and most likely a very exotic scenario (you're the first to complain).

> Setting LDC_VSDIR and resetting VSINSTALLDIR is often not a solution because tools automatically invoked might need an unmodified environment.

That's the way to make LDC auto-setup the environment as you know (temporarily for each `ldc2` process and the `[lld-]link.exe` child process). `LDC_VSDIR` most likely hardly matters for other tools, but `VSINSTALLDIR` does. On non-Windows, you'd probably just use `VSINSTALLDIR="" ldmd2 ...` in order not to affect other tools. A batch file wrapper could probably be used, but that's obviously very ugly.
What tools are you referring to (sorry, no interest to have a look at the DMD CI setup), and why can't you set up the proper environment before building with LDC and switch back afterwards, or ideally, not set up a global environment and then temporarily switch to another platform?

> dmd doesn't have this issue, it always prepends the needed library paths to the LIB variable or passes them directly via /LIBPATH to the linker

I'm reluctant to do that, e.g., because I want the MS tools to have the environment they expect, incl. PATH for implicit tools potentially invoked by the MS linker and whatnot.

**Comment by kinke** [comment] 2020-02-25 17:16
> If a VS environment is setup for one architecture (x64/x86) it is difficult to build tools for another platform

Yeah well, that setup is clearly suboptimal and most likely a very exotic scenario (you're the first to complain).

> Setting LDC_VSDIR and resetting VSINSTALLDIR is often not a solution because tools automatically invoked might need an unmodified environment.

That's the way to make LDC auto-setup the environment as you know (temporarily for each `ldc2` process and the `[lld-]link.exe` child process). `LDC_VSDIR` most likely hardly matters for other tools, but `VSINSTALLDIR` does. On non-Windows, you'd probably just use `VSINSTALLDIR="" ldmd2 ...` in order not to affect other tools. A batch file wrapper could probably be used, but that's obviously very ugly.
What tools are you referring to (sorry, no interest to have a look at the DMD CI setup), and why can't you set up the proper environment before building with LDC and switch back afterwards, or ideally, not set up a global environment and then temporarily switch to another platform?

> dmd doesn't have this issue, it always prepends the needed library paths to the LIB variable or passes them directly via /LIBPATH to the linker

I'm reluctant to do that, e.g., because I want the MS tools to have the environment they expect, incl. PATH for implicit tools potentially invoked by the MS linker and whatnot.

**Comment by kinke** [comment] 2020-02-25 17:38
Btw, this doesn't work with `cl.exe` either, right?

**Comment by rainers** [comment] 2020-02-25 19:49
> What tools are you referring to (sorry, no interest to have a look at the DMD CI setup), and why can't you set up the proper environment before building with LDC and switch back afterwards, or ideally, not set up a global environment and then temporarily switch to another platform?

For example, dmd\test\run.d compiles tools with the host compiler. which then use the CI-built dmd to build tests, sometimes in the same command line using -run.

> Btw, this doesn't work with `cl.exe` either, right?

Yes, but cl.exe has no option to cross compile. 

> I'm reluctant to do that, e.g., because I want the MS tools to have the environment they expect, incl. PATH for implicit tools potentially invoked by the MS linker and whatnot.

Maybe there is another way to do it. For example, if `LDC_VSDIR` is given, why does `VSINSTALLDIR` have to be cleared? Or just detect, that LIB points to the wrong architecture and only adapt it in that case.

**Comment by kinke** [comment] 2020-02-25 20:03
> For example, if LDC_VSDIR is given, why does VSINSTALLDIR have to be cleared?

Because auto-detection is costly (1+ secs) and I want to avoid it if LDC is run inside a pre-set environment, while still allowing the user to set a global `LDC_VSDIR` and not having to clear that.

> For example, dmd\test\run.d compiles tools with the host compiler.

I've switched to `run.d` here too, but I don't use the host compiler for that, and don't see why it should be. The tools need the fresh compiler for testing anyway, plus it limits the available syntax in the tools src files (need to cover a wide range of host compilers; e.g., LDC ltsmaster can't be used).

**Comment by rainers** [comment] 2020-02-25 20:18
> I don't use the host compiler for that, and don't see why it should be.

The reasoning is: if you have introduced a bug in the compiler, compiling run.d (and phobos) with it might cause random crashes that give you no idea what's wrong. If it relies on a stable compiler instead, the test suite will hopefully show you the problem in isolated test cases.

**Comment by kinke** [comment] 2020-02-25 20:25
Oh wow, that's one exotic reasoning! :) - Our CI mostly compiles the compiler using some prebuilt host compiler, then that compiler to re-compile itself, and that's the final compiler being tested. That hasn't been much of an issue wrt. troubleshooting, and the risk of something going bad is much, much, MUCH higher than these tiny tools failing in a hard-to-detect way.

Anyway, so the problem is that LDC as host compiler is also used to compile some other little things, and those aren't built for the same bitness as DMD itself (I've noticed the missing `-m<MODEL>` back then...), so that they fail to link because they need the native bitness?

**Comment by kinke** [comment] 2020-02-25 20:49
Nope that can't be the problem, as a cleared `VSINSTALLDIR` makes LDC set up the required environment in any case, so a missing `-m<MODEL>` shouldn't be a problem.

As you've mentioned `-run`, it's quite likely that the temporary environment set up for the ldc2.exe process leaks into the run D executable (not intentionally). If that was fixed, the D child process would inherit the original environment incl. the cleared `VSINSTALLDIR`; would that be enough or is that variable required for these tools?

**Comment by rainers** [comment] 2020-02-25 20:52
> Our CI mostly compiles the compiler using some prebuilt host compiler, then uses that compiler to re-compile itself, and that's the final compiler being tested.

It might help that the compiler is more or less written in a subset of the language, still compiling with a compiler that is a couple of years old. Anyway, usually the source of the problem isn't hard to find if a PR has reasonable size.

> these tiny tools failing in a hard-to-detect way.

These tools exercise different parts of the language. d_do_test.exe is about 30% the size of dmd.exe, I wouldn't call that tiny in comparison.

> Anyway, so the problem is that LDC as host compiler is also used to compile some other little things,

Probably the issue comes up especially when mixing LDC and DMD, which isn't a regular use case. Whatever I tried, some detail causes a failure because the settings are too entangled. It's unlikely ldmds' fault alone, but working identical to dmd would help.

**Comment by rainers** [comment] 2020-02-25 21:01
> As you've mentioned `-run`, it's quite likely that the temporary environment set up for the ldc2.exe process leaks into the run D executable (not intentionally). If that was fixed, the D child process would inherit the original environment incl. the cleared `VSINSTALLDIR`; would that be enough or is that variable required for these tools?

IIRC dmd received a similar patch recently. I don't think that was the problem, though, but I'd have to go over the failed attempts again and I'm not prepared to do that right now :-/

**Comment by kinke** [comment] 2020-02-25 21:53
I'll have a proposed fix soon, so maybe you can be persuaded to give that prebuilt version a try. ;)

**Comment by kinke** [comment] 2020-02-25 21:59
=> #3341

**Comment by kinke** [comment] 2020-02-26 00:19
In case that's not enough, I wouldn't mind adding another optional env var à la `LDC_VSDIR_FORCE=1` as alternative to clearing `VSINSTALLDIR` in special cases like this.

**Comment by rainers** [comment] 2020-02-26 07:22
Thanks. With keeping the environment and the LDC_VSDIR_FORCE variable set, it looks pretty promising. I haven't tried it on the CI jobs, but a simple test showed that both VSINSTALLDIR and LIB pass through to the spawned program unmodified and it can be compiled with whatever architecture given.

The additional second to run vsdevcmd.bat is a bit annoying, but not much of a problem for a CI job. Maybe ldc could share the respective code from dmd if VSOptions gets moved from link.d to another file?

Side note: with the detection enabled, ldc switches the font for the command prompt window to a raster-font which looks pretty ugly. I suspect this is meant to support UTF8 output, but the code page is still at 437.

**Comment by kinke** [comment] 2020-02-26 16:19
> Side note: with the detection enabled, ldc switches the font for the command prompt window to a raster-font which looks pretty ugly.

Yeah, noticed that ugliness too, fixed now.

> The additional second to run vsdevcmd.bat is a bit annoying, but not much of a problem for a CI job. Maybe ldc could share the respective code from dmd if VSOptions gets moved from link.d to another file?

I haven't looked at that code (presumably yours) yet; as long as you are confident that it's a near-perfect replacement for `vsdevcmd.bat` incl. auto-detection logic via `vswhere.exe` (and registry lookups for older VS versions) and not likely to break with future VS versions, then it'd be an option. The batch file is ugly and slow, but it makes sure the environment is fully set up, and its 'API' is very stable and unlikely to be dropped soon.

**Comment by rainers** [comment] 2020-03-04 07:24
I guess with #3341 merged, this could be closed now. Or do you plan to keep it for a reminder for this refactoring:

> as long as you are confident that it's a near-perfect replacement for `vsdevcmd.bat` 

I guess this depends on what Microsoft changes in the future.

> incl. auto-detection logic via `vswhere.exe` (and registry lookups for older VS versions)

This is implemented via the recommended COM interface just as within vswhere, so should be fine.

> and not likely to break with future VS versions, then it'd be an option.

You never know ;-)

I have extracted VSOptions here https://github.com/dlang/dmd/pull/10860

**Comment by kinke** [comment] 2020-03-05 19:55
Okay let's close then. Thx for the heads-up and extracting the implementation; I'll be reminded automatically when merging v2.092.

**Closed by kinke** 2020-03-05 19:55 UTC

**Comment by kinke** [comment] 2020-03-05 20:00
Btw, would you welcome this fix to be released soon? The LDC-specific ModuleInfo regression (#3346) probably justifies a v1.20.1 patch release, so I could merge this into that as well if you care about it.

**Comment by rainers** [comment] 2020-03-05 20:08
I think it will make using ldc a bit easier, but It's not urgent. I've switched the affected CIs to use dmd for the testing tools while still compiling dmd with LDC.
