### ISSUE TITLE
Can't find gcc x86 builtins in v1.32

### ISSUE THREAD

**Issue by alexeiverbny** [ldc-developers/ldc#4370] opened 2023-04-12 17:26 UTC
The following code used to work with v1.30: 
```
    import ldc.gccbuiltins_x86 : __builtin_ia32_packusdw128;
    short8 pack_i32_u16(int4 a, int4 b) pure @safe nothrow @nogc
    {
        return __builtin_ia32_packusdw128(a, b);
    }
```

after upgrading to v1.32 I get the following error:
```
Error: module `ldc.gccbuiltins_x86` import `__builtin_ia32_packusdw128` not found
```

I am having a similar issue with `__builtin_ia32_pext_di`

Is this expected? If so, is there a different way to use these intrinsics?

**Comment by kinke** [comment] 2023-04-12 18:17
This is a duplicate of https://github.com/ldc-developers/ldc/issues/4347. Needs a new compiler release.

**Closed by kinke** 2023-04-12 18:17 UTC
