### ISSUE TITLE
use -fvisibility=hidden  with c objects can not compile

### ISSUE THREAD

**Issue by patrickkh7788** [ldc-developers/ldc#2922] opened 2018-11-22 22:17 UTC
For example I build sqlite object file with D source into  so (-shared -fvisibility=hidden), result with undefined reference to `abort' and all sqlite symbols. remove -fvisibility=hidden it can build and pass test.

I try add -L-lc, still report missing symbols. (test on android termux arm32).

please provide example  how it work with c static lib or object files.

**Comment by kinke** [comment] 2018-11-22 23:46
> please provide example

Sure, we have nothing better to do with our spare time. I don't recall a single piece of D source you provided in any of your issues so far, so maybe it should be you providing some code. I don't mean to be too rude, but this kind of issues (hey, I'm using some cmdline switch I don't really understand, and it's not working) aren't helpful (and I'm quite sure the problem isn't LDC).

**Comment by kinke** [comment] 2018-11-23 00:14
In case you're fwd declaring C functions to be linked in from other shared libs (sqlite etc.) yourself, i.e., not importing them from a 3rd party module, and only using those functions inside that module (compiled with the new switch), you might currently need to fwd declare them as `export`. But that's just a guess after quickly looking up the PR again.

**Comment by kinke** [comment] 2018-11-23 00:30
Hmm, seems like `isImportedSymbol()` is not what I was expecting. We should probably declare all functions with public visibility and only optionally hide them when defining them; this is different to Windows, where the extra `export` for the `dllimport` attribute of symbols provided by other DLLs is to be expected (extra symbol name prefix etc.).

**Comment by kinke** [comment] 2018-11-23 02:33
=> #2923

**Comment by kinke** [comment] 2018-11-23 03:30
I figured the issue; the feature is really unusable as it is in beta2, but fixed in the PR. So thx, your report did help, but it's just considerably more work if I have to study the code to form a hypothesis & come up with a testcase myself.

**Comment by patrickkh7788** [comment] 2018-11-23 05:14
Understood, I will try provide test case to help reduce the work in future issues.

**Closed** 2018-12-03 20:06 UTC
