### ISSUE TITLE
undefined symbol on hidden function: LDC should detect usage of symbols in inline assembly for LTO builds and keep them

### ISSUE THREAD

**Issue by ljmf00-wekaio** [ldc-developers/ldc#4597] opened 2024-03-19 13:04 UTC
For the following code:

```
    extern(C) void _trampoline() nothrow @naked {
        pragma(inline, false);
        __asm(`
            mov  x0, x19;  // fn
            mov  x1, x20;  // opaque
            bl _wrapper`, "");
    }
```
Compiling this under `aarch64` target and using LTO makes `_wrapper` undefined symbol. The reason is that we seem to delete symbols prematurely before LTO is processed on the linker side, throwing that function away and therefore getting this error.

NOTE: I'm pretty sure this is architecture agnostic issue, but didn't test it.

CC @JohanEngelen

**Comment by kinke** [comment] 2024-03-19 15:43
You'll probably have to pass in the function symbol as a parameter, so that it's referenced at the IR level, not at the asm level.

**Comment by JohanEngelen** [comment] 2024-03-19 18:51
I need a full testcase, because I cannot reproduce it with:

```d
import ldc.attributes;
import ldc.llvmasm;

extern(C) void _trampoline() nothrow @naked {
        pragma(inline, false);
        __asm(`
            mov  x0, x19;  // fn
            mov  x1, x20;  // opaque
            bl _wrapper`, "");
}

extern(C)
void wrapper() {
}
```
```
❯ ldc2 -c testasm.d -O

❯ nm testasm.o
0000000000000028 S __D7testasm11__moduleRefZ
0000000000000018 D __D7testasm12__ModuleInfoZ
0000000000000000 T __trampoline
0000000000000010 T _wrapper
0000000000000000 t ltmp0
0000000000000018 d ltmp1
0000000000000028 s ltmp2
0000000000000030 s ltmp3
```
```
❯ ldc2 -c testasm.d -O -flto=full

❯ llvm-nm testasm.o
---------------- W __D7testasm11__moduleRefZ
---------------- D __D7testasm12__ModuleInfoZ
---------------- T __trampoline
---------------- T _wrapper
```

**Comment by JohanEngelen** [comment] 2024-03-19 19:01
This is an issue with LTO linker, not something that LDC can do something about easily (it will be a lot of trouble to detect symbols inside inline assembly, without false positives).
Applying `@ldc.attributes.assumeUsed` to `wrapper` definition does solve the problem, hope that's an acceptable workaround.

There is an LLVM bug report about this issue: https://github.com/llvm/llvm-project/issues/76046

Closing here.  (Reopen if you disagree)

**Closed by JohanEngelen** 2024-03-19 19:01 UTC

**Comment by ljmf00-wekaio** [comment] 2024-03-20 05:10
I understand its edgy to do it from inline asm in the first place, requiring to parse it and even with that it is clumsy, specially this being a very particular case, so we can live with a single `@ldc.attributes.assumeUsed` on the fiber trampoline wrapper. I think no one should do `jump` instead of `call`, except for these cases, otherwise I think LLVM would have some facility to do this in the IR.

Maybe there is. If you know, let me know :)
