### ISSUE TITLE
ldc-1.0.0 and ldc-master segfault with 'out' parameters.

### ISSUE THREAD

**Issue by antoniocorbi** [ldc-developers/ldc#1576] opened 2016-06-22 16:15 UTC
I've reduced a core generation in ldc-1.0.0/ldc-master to this simple example:

```D
// compile with: ldc -c   or ldc-git -c
class BWImage {
public void get_rgb (in int x, in int y, out ubyte r, out ubyte g, out ubyte b)
   in {
      assert ( x>=0, "Pixmap.get_rgb 'x' coord must be >=0.");
      assert ( x < 100, "Pixmap.get_rgb 'x' coord must be < width.");
      assert ( y>=0, "Pixmap.get_rgb 'y' coord must be >=0.");
      assert ( y < 100, "Pixmap.get_rgb 'y' coord must be < height.");
    }
  body {
    r = g = b = 0;
    ubyte e[4];

    r = e[0]; g = e[1]; b = e[2];
  }
}
```
1. If you omit the in {...} block, it compiles ok.
1. If you keep the in {...} block but change the 'out' parameters to 'ref', it compiles ok.
1. If you leave it as it is, it makes ldc/ldc-git segfault

This is archlinux with
1. ldc:
LDC - the LLVM D compiler (1.0.0):
  based on DMD v2.070.2 and LLVM 3.8.0
  built with DMD64 D Compiler v2.071.0
  Default target: x86_64-unknown-linux-gnu
  Host CPU: core2
2. ldc-git:
LDC - the LLVM D compiler (170502):
  based on DMD v2.071.1 and LLVM 3.8.0
  built with DMD64 D Compiler v2.071.0
  Default target: x86_64-unknown-linux-gnu
  Host CPU: core2

**Comment by kinke** [comment] 2016-06-22 21:46
This is a duplicate of #1543. Closing.

**Closed by kinke** 2016-06-22 21:46 UTC
