### ISSUE TITLE
Interface downcast doesn't get upcast when calling through

### ISSUE THREAD

**Issue by etcimon** [ldc-developers/ldc#729] opened 2014-09-30 18:36 UTC
I've been trying to isolate this for a couple days but can't get through with it. It's an issue with interface (dynamic) casting, but every test I make with in isolated applications runs just fine.

Anyways, trying my luck here with this complicated problem, maybe someone knows something can be improved somewhere.. It happens in my native implementation of vibe.d : 

https://github.com/etcimon/vibe.d/blob/native-events/source/vibe/http/server.d#L1220

Notice I've upcast manually the `TCPConnection` line 1214 because otherwise the `LibasyncTCPConnection` (twice) derived instance has a `this` instance as a copy of the .vtbl() reference pointer when calling the overriden methods. It makes it impossible to modify the state of the object at any time and it's (I think) the only obstacle preventing it from being compiled completely with LDC. This also causes errors with `invariant`, so I had to disable core.rt.invariant and compile without it to diagnose the issue.

I can't really do much more with this workaround because I'd have to upcast in every delegate, and TCPConnection is used everywhere. I've been using the latest LDC compiled with GCC 4.8 and using LLVM 3.4

Also, I'm using GC.malloc.

Any ideas?

**Comment by kinke** [comment] 2016-08-21 00:02
@etcimon: Still an issue or safe to be closed?

**Comment by kinke** [comment] 2017-10-30 01:01
Closing due to lack of information/reproducibility.

**Closed by kinke** 2017-10-30 01:01 UTC
