### ISSUE TITLE
linking error on M1 processors

### ISSUE THREAD

**Issue by gedaiu** [ldc-developers/ldc#3997] opened 2022-06-07 10:35 UTC
building with ldc 1.30.0-beta-1 I get this linker error: 

```
ld: unaligned pointer(s) for architecture arm64
```

It looks like this happens while using older compilers too.

This is a full log for the https://github.com/D-Programming-Deimos/openssl repo:

```
➜  openssl git:(master) ✗ dub
Running pre-generate commands for openssl...
binary    ....../bin/ldc2
version   1.30.0-beta1 (DMD v2.100.0, LLVM 14.0.3)
config    .......etc/ldc2.conf (arm64-apple-darwin21.5.0)
predefs   Have_script LDC all D_Version2 assert D_PreConditions D_PostConditions D_Invariants D_ModuleInfo D_Exceptions D_TypeInfo AArch64 ARM_HardFloat D_HardFloat LittleEndian D_LP64 D_PIC OSX darwin Posix CppRuntime_Clang LDC_LLVM_1400 D_ObjectiveC
parse     generate_version
importall generate_version
import    object	(............/bin/../import/object.d)
import    core.attribute	(............/bin/../import/core/attribute.d)
import    ldc.attributes	(............/bin/../import/ldc/attributes.d)
import    core.internal.hash	(............/bin/../import/core/internal/hash.d)
import    core.internal.traits	(............/bin/../import/core/internal/traits.d)
import    core.internal.entrypoint	(............/bin/../import/core/internal/entrypoint.d)
import    core.internal.array.appending	(............/bin/../import/core/internal/array/appending.d)
import    core.internal.array.comparison	(............/bin/../import/core/internal/array/comparison.d)
import    core.internal.array.equality	(............/bin/../import/core/internal/array/equality.d)
import    core.internal.array.casting	(............/bin/../import/core/internal/array/casting.d)
import    core.internal.array.concatenation	(............/bin/../import/core/internal/array/concatenation.d)
import    core.internal.array.construction	(............/bin/../import/core/internal/array/construction.d)
import    core.internal.array.capacity	(............/bin/../import/core/internal/array/capacity.d)
import    core.internal.dassert	(............/bin/../import/core/internal/dassert.d)
import    core.atomic	(............/bin/../import/core/atomic.d)
import    core.internal.attributes	(............/bin/../import/core/internal/attributes.d)
import    core.internal.atomic	(............/bin/../import/core/internal/atomic.d)
import    ldc.intrinsics	(............/bin/../import/ldc/intrinsics.di)
import    core.internal.destruction	(............/bin/../import/core/internal/destruction.d)
import    core.internal.moving	(............/bin/../import/core/internal/moving.d)
import    core.internal.postblit	(............/bin/../import/core/internal/postblit.d)
import    core.internal.switch_	(............/bin/../import/core/internal/switch_.d)
import    core.lifetime	(............/bin/../import/core/lifetime.d)
import    core.builtins	(............/bin/../import/core/builtins.d)
import    std.algorithm	(............/bin/../import/std/algorithm/package.d)
import    std.algorithm.comparison	(............/bin/../import/std/algorithm/comparison.d)
import    std.functional	(............/bin/../import/std/functional.d)
import    std.meta	(............/bin/../import/std/meta.d)
import    std.traits	(............/bin/../import/std/traits.d)
import    std.range.primitives	(............/bin/../import/std/range/primitives.d)
import    std.conv	(............/bin/../import/std/conv.d)
import    std.ascii	(............/bin/../import/std/ascii.d)
import    std.typecons	(............/bin/../import/std/typecons.d)
import    std.format.spec	(............/bin/../import/std/format/spec.d)
import    std.format.write	(............/bin/../import/std/format/write.d)
import    std.format.internal.write	(............/bin/../import/std/format/internal/write.d)
import    std.internal.attributes	(............/bin/../import/std/internal/attributes.d)
import    std.range	(............/bin/../import/std/range/package.d)
import    std.array	(............/bin/../import/std/array.d)
import    std.range.interfaces	(............/bin/../import/std/range/interfaces.d)
import    std.algorithm.iteration	(............/bin/../import/std/algorithm/iteration.d)
import    std.algorithm.mutation	(............/bin/../import/std/algorithm/mutation.d)
import    std.algorithm.searching	(............/bin/../import/std/algorithm/searching.d)
import    std.algorithm.setops	(............/bin/../import/std/algorithm/setops.d)
import    std.algorithm.sorting	(............/bin/../import/std/algorithm/sorting.d)
import    std.file	(............/bin/../import/std/file.d)
import    core.time	(............/bin/../import/core/time.d)
import    core.exception	(............/bin/../import/core/exception.d)
import    core.stdc.time	(............/bin/../import/core/stdc/time.d)
import    core.sys.posix.stdc.time	(............/bin/../import/core/sys/posix/stdc/time.d)
import    core.sys.posix.sys.types	(............/bin/../import/core/sys/posix/sys/types.d)
import    core.sys.posix.config	(............/bin/../import/core/sys/posix/config.d)
import    core.stdc.config	(............/bin/../import/core/stdc/config.d)
import    core.stdc.stdint	(............/bin/../import/core/stdc/stdint.d)
import    core.stdc.stddef	(............/bin/../import/core/stdc/stddef.d)
import    core.stdc.signal	(............/bin/../import/core/stdc/signal.d)
import    core.stdc.wchar_	(............/bin/../import/core/stdc/wchar_.d)
import    core.stdc.stdarg	(............/bin/../import/core/stdc/stdarg.d)
import    core.stdc.stdio	(............/bin/../import/core/stdc/stdio.d)
import    core.internal.string	(............/bin/../import/core/internal/string.d)
import    core.sys.posix.time	(............/bin/../import/core/sys/posix/time.d)
import    core.sys.posix.signal	(............/bin/../import/core/sys/posix/signal.d)
import    core.sys.posix.sys.time	(............/bin/../import/core/sys/posix/sys/time.d)
import    core.sys.posix.sys.select	(............/bin/../import/core/sys/posix/sys/select.d)
import    core.sys.darwin.mach.kern_return	(............/bin/../import/core/sys/darwin/mach/kern_return.d)
import    std.datetime.date	(............/bin/../import/std/datetime/date.d)
import    std.datetime.systime	(............/bin/../import/std/datetime/systime.d)
import    std.exception	(............/bin/../import/std/exception.d)
import    std.format	(............/bin/../import/std/format/package.d)
import    std.format.read	(............/bin/../import/std/format/read.d)
import    std.format.internal.read	(............/bin/../import/std/format/internal/read.d)
import    std.datetime.timezone	(............/bin/../import/std/datetime/timezone.d)
import    core.stdc.errno	(............/bin/../import/core/stdc/errno.d)
import    core.stdc.stdlib	(............/bin/../import/core/stdc/stdlib.d)
import    core.stdc.string	(............/bin/../import/core/stdc/string.d)
import    std.internal.cstring	(............/bin/../import/std/internal/cstring.d)
import    core.sys.posix.dirent	(............/bin/../import/core/sys/posix/dirent.d)
import    core.sys.posix.fcntl	(............/bin/../import/core/sys/posix/fcntl.d)
import    core.sys.posix.sys.stat	(............/bin/../import/core/sys/posix/sys/stat.d)
import    core.sys.posix.unistd	(............/bin/../import/core/sys/posix/unistd.d)
import    core.sys.posix.inttypes	(............/bin/../import/core/sys/posix/inttypes.d)
import    core.stdc.inttypes	(............/bin/../import/core/stdc/inttypes.d)
import    core.sys.posix.utime	(............/bin/../import/core/sys/posix/utime.d)
import    std.path	(............/bin/../import/std/path.d)
import    std.process	(............/bin/../import/std/process.d)
import    core.thread	(............/bin/../import/core/thread/package.d)
import    core.thread.fiber	(............/bin/../import/core/thread/fiber.d)
import    core.thread.osthread	(............/bin/../import/core/thread/osthread.d)
import    core.memory	(............/bin/../import/core/memory.d)
import    core.sys.darwin.pthread	(............/bin/../import/core/sys/darwin/pthread.d)
import    core.sys.posix.pthread	(............/bin/../import/core/sys/posix/pthread.d)
import    core.sys.posix.sched	(............/bin/../import/core/sys/posix/sched.d)
import    core.sys.darwin.mach.port	(............/bin/../import/core/sys/darwin/mach/port.d)
import    core.thread.threadbase	(............/bin/../import/core/thread/threadbase.d)
import    core.thread.context	(............/bin/../import/core/thread/context.d)
import    core.thread.types	(............/bin/../import/core/thread/types.d)
import    core.sync.mutex	(............/bin/../import/core/sync/mutex.d)
import    core.sync.exception	(............/bin/../import/core/sync/exception.d)
import    ldc.llvmasm	(............/bin/../import/ldc/llvmasm.di)
import    core.sys.posix.ucontext	(............/bin/../import/core/sys/posix/ucontext.d)
import    core.sys.posix.semaphore	(............/bin/../import/core/sys/posix/semaphore.d)
import    core.sys.posix.stdlib	(............/bin/../import/core/sys/posix/stdlib.d)
import    core.sys.posix.sys.wait	(............/bin/../import/core/sys/posix/sys/wait.d)
import    core.sys.darwin.mach.thread_act	(............/bin/../import/core/sys/darwin/mach/thread_act.d)
import    core.thread.threadgroup	(............/bin/../import/core/thread/threadgroup.d)
import    std.stdio	(............/bin/../import/std/stdio.d)
import    core.sys.posix.stdio	(............/bin/../import/core/sys/posix/stdio.d)
import    std.string	(............/bin/../import/std/string.d)
import    std.uni	(............/bin/../import/std/uni/package.d)
import    std.internal.unicode_tables	(............/bin/../import/std/internal/unicode_tables.d)
semantic  generate_version
import    core.internal.lifetime	(............/bin/../import/core/internal/lifetime.d)
import    std.utf	(............/bin/../import/std/utf.d)
entry     main      	scripts/generate_version.d
semantic2 generate_version
semantic3 generate_version
import    std.internal.memory	(............/bin/../import/std/internal/memory.d)
import    core.internal.array.utils	(............/bin/../import/core/internal/array/utils.d)
import    core.bitop	(............/bin/../import/core/bitop.d)
import    core.checkedint	(............/bin/../import/core/checkedint.d)
import    core.internal.convert	(............/bin/../import/core/internal/convert.d)
import    std.math.traits	(............/bin/../import/std/math/traits.d)
import    std.bitmanip	(............/bin/../import/std/bitmanip.d)
import    std.system	(............/bin/../import/std/system.d)
import    std.internal.unicode_grapheme	(............/bin/../import/std/internal/unicode_grapheme.d)
import    std.math.algebraic	(............/bin/../import/std/math/algebraic.d)
import    core.math	(............/bin/../import/core/math.d)
import    core.stdc.math	(............/bin/../import/core/stdc/math.d)
import    std.math.hardware	(............/bin/../import/std/math/hardware.d)
import    core.stdc.fenv	(............/bin/../import/core/stdc/fenv.d)
import    std.encoding	(............/bin/../import/std/encoding.d)
GC stats  1M used, 4M free, 5M total
code      generate_version
@(#)PROGRAM:ld  PROJECT:ld64-764
BUILD 11:29:07 May 17 2022
configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
Library search paths:
	............/lib
	/usr/local/lib
	/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib
Framework search paths:
	/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/
ld: warning: pointer not aligned at address 0x1002A0D8E (anon + 3470 from /var/folders/q8/npwcm3sn6mn5lf44bf1m2t8w0000gp/T/.dub/build/script-~master/application-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-A629722488BD0D73076F12F337519DC2/script.o)
ld: unaligned pointer(s) for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: /usr/bin/cc failed with status: 1
ldc2 failed with exit code 1.
Command failed with exit code 2: .........../bin/dub scripts/generate_version.d
```

**Comment by Geod24** [comment] 2022-06-07 10:40
Does it only happen with the build script ? Try providing a version explicitly to see if it's not just being weird with the invocation of `preGenerateCommands`

**Comment by kinke** [comment] 2022-06-07 10:47
Duplicate of #3864; see workarounds there.

**Closed by kinke** 2022-06-07 10:47 UTC
