### ISSUE TITLE
Linking error building ocean library with ldc-master (37a27eb9)

### ISSUE THREAD

**Issue by AndrejMitrovic** [ldc-developers/ldc#3590] opened 2020-10-20 07:22 UTC
https://github.com/sociomantic-tsunami/ocean/commit/ec811cba

```
$ dub test --compiler=$HOME/Downloads/ldc2-37a27eb9-osx-x86_64/bin/ldc2

Linking...
Undefined symbols for architecture x86_64:
  "__D5ocean4core5array17DefaultPredicatesQt__T6IsLessTG2aZQm6opCallFNaNbNiNfIG2aIQeZb", referenced from:
      __D5ocean4core5array8Mutation__T4sortTG2aTSQBoQBlQBj17DefaultPredicatesQt__T6IsLessTQBuZQmZQChFAQCgQCfZ5equivMFNaNbNiNfQDdQDgZb in ocean-test-library.o
      __D5ocean4core5array8Mutation__T4sortTG2aTSQBoQBlQBj17DefaultPredicatesQt__T6IsLessTQBuZQmZQChFAQCgQCfZ13insertionSortMFNaNbNiNfmmZv in ocean-test-library.o
      __D5ocean4core5array8Mutation__T4sortTG2aTSQBoQBlQBj17DefaultPredicatesQt__T6IsLessTQBuZQmZQChFAQCgQCfZ8medianOfMFNaNbNiNfmmmZm in ocean-test-library.o
      __D5ocean4core5array8Mutation__T4sortTG2aTSQBoQBlQBj17DefaultPredicatesQt__T6IsLessTQBuZQmZQChFAQCgQCfZ9quicksortMFNaNbNiNfmmmZv in ocean-test-library.o
  "__D5ocean4core5array17DefaultPredicatesQt__T6IsLessTaZQk6opCallFNaNbNiNfIaIaZb", referenced from:
      __D5ocean4core5array14Transformation__T7unionOfTaTSQBwQBtQBr17DefaultPredicatesQt__T6IsLessTaZQkZQCgFNaNbNfIAaIQdQClZAa in ocean-test-library.o
      __D5ocean4core5array14Transformation__T14intersectionOfTaTSQCeQCbQBz17DefaultPredicatesQt__T6IsLessTaZQkZQCoFNaNbNfIAaIQdQClZAa in ocean-test-library.o
      __D5ocean4core5array14Transformation__T11missingFromTaTSQCbQByQBw17DefaultPredicatesQt__T6IsLessTaZQkZQClFNaNbNfIAaIQdQClZAa in ocean-test-library.o
      __D5ocean4core5array14Transformation__T12differenceOfTaTSQCcQBzQBx17DefaultPredicatesQt__T6IsLessTaZQkZQCmFNaNbNfIAaIQdQClZAa in ocean-test-library.o
      __D5ocean4core5array6Search__T8includesTaTSQBoQBlQBj17DefaultPredicatesQt__T6IsLessTaZQkZQChFNaNbNiNfIAaIQdQCnZb in ocean-test-library.o
      __D5ocean4core5array8Mutation__T4sortTaTSQBmQBjQBh17DefaultPredicatesQt__T6IsLessTaZQkZQCdFAaQCbZ5equivMFNaNbNiNfaaZb in ocean-test-library.o
      __D5ocean4core5array8Mutation__T4sortTaTSQBmQBjQBh17DefaultPredicatesQt__T6IsLessTaZQkZQCdFAaQCbZ13insertionSortMFNaNbNiNfmmZv in ocean-test-library.o
      ...
  "__D5ocean4core5array17DefaultPredicatesQt__T6IsLessTdZQk6opCallFNaNbNiNfIdIdZb", referenced from:
      __D5ocean4core5array8Mutation__T11quickselectTdTSQBuQBrQBp17DefaultPredicatesQt__T6IsLessTdZQkZQClFAdmQCcmZ9partitionFQtmmmQCxZm in ocean-test-library.o
  "__D5ocean4core5array17DefaultPredicatesQt__T6IsLessTiZQk6opCallFNaNbNiNfIiIiZb", referenced from:
      __D5ocean4core5array8Mutation__T4sortTiTSQBmQBjQBh17DefaultPredicatesQt__T6IsLessTiZQkZQCdFAiQCbZ5equivMFNaNbNiNfiiZb in ocean-test-library.o
      __D5ocean4core5array8Mutation__T4sortTiTSQBmQBjQBh17DefaultPredicatesQt__T6IsLessTiZQkZQCdFAiQCbZ13insertionSortMFNaNbNiNfmmZv in ocean-test-library.o
      __D5ocean4core5array8Mutation__T4sortTiTSQBmQBjQBh17DefaultPredicatesQt__T6IsLessTiZQkZQCdFAiQCbZ8medianOfMFNaNbNiNfmmmZm in ocean-test-library.o
      __D5ocean4core5array8Mutation__T4sortTiTSQBmQBjQBh17DefaultPredicatesQt__T6IsLessTiZQkZQCdFAiQCbZ9quicksortMFNaNbNiNfmmmZv in ocean-test-library.o
      __D5ocean4core5array8Mutation__T11quickselectTiTSQBuQBrQBp17DefaultPredicatesQt__T6IsLessTiZQkZQClFAimQCcmZ9partitionFQtmmmQCxZm in ocean-test-library.o
  "__D5ocean4core5array17DefaultPredicatesQt__T7IsEqualTSQBzQBwQBu6Search18__unittest_L778_C1FZ4HashZQCc6opCallFISQEeQEbQDzQCfQCbFZQBkIQwZb", referenced from:
      __D5ocean4core5array6Search__T4findTSQBiQBfQBdQBa18__unittest_L778_C1FZ4HashTSQCxQCuQCs17DefaultPredicatesQt__T7IsEqualTQDgZQnZQDtFIASQFbQEyQEwQEtQDtFZQDcIQwQDcZm in ocean-test-library.o
  "__D5ocean4core5array17DefaultPredicatesQt__T7IsEqualTaZQl6opCallFNaNbNiNfIaIaZb", referenced from:
      __D5ocean4core5array6Search__T4findTaTSQBkQBhQBf17DefaultPredicatesQt__T7IsEqualTaZQlZQCeFNaNbNiNfIAaIaQCnZm in ocean-test-library.o
      __D5ocean4core5array6Search__T4findTaTSQBkQBhQBf17DefaultPredicatesQt__T7IsEqualTaZQlZQCeFNaNbNiNfIAaIQdQCoZm in ocean-test-library.o
      __D5ocean4core5array6Search__T5rfindTaTSQBlQBiQBg17DefaultPredicatesQt__T7IsEqualTaZQlZQCfFNaNbNiNfIAaIaQCnZm in ocean-test-library.o
      __D5ocean4core5array6Search__T5rfindTaTSQBlQBiQBg17DefaultPredicatesQt__T7IsEqualTaZQlZQCfFNaNbNiNfIAaIQdQCoZm in ocean-test-library.o
      __D5ocean4core5array6Search__T5kfindTaTSQBlQBiQBg17DefaultPredicatesQt__T7IsEqualTaZQlZQCfFNbIAaIQdQCiZm in ocean-test-library.o
      __D5ocean4core5array6Search__T7findAdjTaTSQBnQBkQBi17DefaultPredicatesQt__T7IsEqualTaZQlZQChFNaNbNiNfIAaQClZm in ocean-test-library.o
      __D5ocean4core5array6Search__T8mismatchTaTSQBoQBlQBj17DefaultPredicatesQt__T7IsEqualTaZQlZQCiFNaNbNiNfIAaIQdQCoZm in ocean-test-library.o
      ...
  "__D5ocean4core5array17DefaultPredicatesQt__T7IsEqualTiZQl6opCallFNaNbNiNfIiIiZb", referenced from:
      __D5ocean4core5array6Search__T4findTiTSQBkQBhQBf17DefaultPredicatesQt__T7IsEqualTiZQlZQCeFNaNbNiNfIAiIQdQCoZm in ocean-test-library.o
      __D5ocean4core5array6Search__T5rfindTiTSQBlQBiQBg17DefaultPredicatesQt__T7IsEqualTiZQlZQCfFNaNbNiNfIAiIiQCnZm in ocean-test-library.o
      __D5ocean4core5array6Search__T5rfindTiTSQBlQBiQBg17DefaultPredicatesQt__T7IsEqualTiZQlZQCfFNaNbNiNfIAiIQdQCoZm in ocean-test-library.o
      __D5ocean4core5array6Search__T4findTiTSQBkQBhQBf17DefaultPredicatesQt__T7IsEqualTiZQlZQCeFNaNbNiNfIAiIiQCnZm in ocean-test-library.o
      __D5ocean4core5array6Search__T5kfindTiTSQBlQBiQBg17DefaultPredicatesQt__T7IsEqualTiZQlZQCfFNbIAiIQdQCiZm in ocean-test-library.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: /usr/bin/cc failed with status: 1
/Users/andrejmitrovic/Downloads/ldc2-37a27eb9-osx-x86_64/bin/ldc2 failed with exit code 1.
```

Our CI showed linking failures on Linux, OSX, and Windows.

**Comment by JohanEngelen** [comment] 2020-10-20 11:20
Can you check if the missing symbols do exist with a small change in their name? (it could be a template function attribute deduction issue)
For example, check if `__D5ocean4core5array17DefaultPredicatesQt__T6IsLessTG2aZQm6opCall` (without the attributes at the end) exists in one of the linked binaries.

**Comment by kinke** [comment] 2020-10-20 13:03
I bet it fails with DMD 2.094.1 too then, and is probably related to https://github.com/dlang/dmd/pull/11874. Can you give a commit hash for ldc-master where it still worked, just to see if the previous variant in https://github.com/dlang/dmd/pull/11838 worked?

**Comment by kinke** [comment] 2020-10-21 14:02
Confirmed, see https://github.com/dlang/dmd/pull/11874#issuecomment-713600187.

**Comment by ibuclaw** [comment] 2020-10-21 19:34
It is unlikely to do anything different, but did you build from a clean cache?

**Comment by kinke** [comment] 2020-10-21 19:53
I'm pretty sure stale artifacts weren't the cause ;) - I did a `dub clean` before each run.

**Comment by Geod24** [comment] 2020-10-22 02:31
The issue triggers reliably in our CI, which always starts from a clean slate.

**Comment by kinke** [comment] 2020-10-23 19:03
Should have been fixed in https://github.com/dlang/dmd/pull/11896, which is in master now. Please confirm.

**Closed** 2020-10-27 16:38 UTC
