### ISSUE TITLE
Latest ldc breaks D-Scanner

### ISSUE THREAD

**Issue by RazvanN7** [ldc-developers/ldc#3974] opened 2022-04-29 10:11 UTC
As it can be observed in: https://github.com/dlang-community/D-Scanner/pull/865

**Comment by PetarKirov** [comment] 2022-04-29 10:17
Should be fixed by https://github.com/dlang-community/libdparse/pull/458

**Comment by kinke** [comment] 2022-04-29 11:51
I often wonder why I bother with changelog and betas - this ABI change was announced more than 1.5 months ago.

**Closed by kinke** 2022-04-29 11:51 UTC

**Comment by PetarKirov** [comment] 2022-04-29 12:32
I agree that betas by themselves are not very useful since very few people bother to try them (same for DMD and many heaps of other software). Having a BuildKite pipeline for LDC would provide much more actionable feedback in comparison.

**Comment by RazvanN7** [comment] 2022-04-29 13:04
> I often wonder why I bother with changelog and betas - this ABI change was announced more than 1.5 months ago.

If you are hinting that I should not have reported this issue and instead read the ldc changelog, I want to point out that we have discovered this issue while using a fork of a project (d-scanner) that depends on libdparse, where the actual issue was. I looked at what was recently merged in d-scanner and ldc and saw the abi change however, I was not expecting that libdparse was using any inline assembly, so even looking at the changelog it was not obvious at all what the problem was.

The real issue here is that the update to a more recent version of ldc is done automatically and users of the library are left to double guess what the breakage is.

**Comment by kinke** [comment] 2022-04-29 13:19
> Having a BuildKite pipeline for LDC would provide much more actionable feedback in comparison.

I disagree. IMO, lib repos should have a cron CI job *and* use the latest compiler releases, incl. prereleases. At least for LDC, `ldc-beta` is a bit of a misnomer - it's not the latest beta, but the latest (pre)release, and so ideally suited to catch regressions early.

> If you are hinting that I should not have reported this issue and instead read the ldc changelog

Nope, the hint was more like 'check/file the issue in the lib repo first', before filing a one-sentence compiler bug report. We're almost family in the tiny dlang universe, granted ;) - but imagine someone filing such an issue for clang whenever some project breaks. :)
