### ISSUE TITLE
ld: unaligned pointer(s) for architecture arm64

### ISSUE THREAD

**Issue by zoujiaqing** [ldc-developers/ldc#3989] opened 2022-05-20 16:07 UTC
os: macOS
cpu: M1 Pro
ldc version: 1.30 beta1

```sh
zoujiaqing@zoujiaqings-MacBook-Pro projects % git clone https://github.com/kerisy/archttp.git
Cloning into 'archttp'...
remote: Enumerating objects: 368, done.
remote: Counting objects: 100% (368/368), done.
remote: Compressing objects: 100% (237/237), done.
remote: Total 368 (delta 179), reused 192 (delta 80), pack-reused 0
Receiving objects: 100% (368/368), 85.86 KiB | 1.07 MiB/s, done.
Resolving deltas: 100% (179/179), done.
zoujiaqing@zoujiaqings-MacBook-Pro projects % cd archttp/examples/httpserver 
zoujiaqing@zoujiaqings-MacBook-Pro httpserver % dub run
Performing "debug" build using /Users/zoujiaqing/.local/ldc/bin/ldc2 for aarch64, arm_hardfloat.
unit-threaded:from 0.10.8: target for configuration "library" is up to date.
unit-threaded:exception 0.10.8: target for configuration "library" is up to date.
unit-threaded:assertions 0.10.8: target for configuration "library" is up to date.
unit-threaded:integration 0.10.8: target for configuration "library" is up to date.
unit-threaded:mocks 0.10.8: target for configuration "library" is up to date.
unit-threaded:property 0.10.8: target for configuration "default" is up to date.
unit-threaded:runner 0.10.8: target for configuration "library" is up to date.
unit-threaded 0.10.8: target for configuration "library" is up to date.
nbuff 0.1.14: target for configuration "std" is up to date.
geario 0.0.1: target for configuration "library" is up to date.
archttp ~main: building configuration "library"...
../../../../.dub/packages/nbuff-0.1.14/nbuff/source/nbuff/buffer.d(74,25): Deprecation: `catch` statement without an exception specification is deprecated
../../../../.dub/packages/nbuff-0.1.14/nbuff/source/nbuff/buffer.d(74,25):        use `catch(Throwable)` for old behavior
'-sse4.2' is not a recognized feature for this target (ignoring feature)
SSE: false
httpserver ~master: building configuration "application"...
../../../../.dub/packages/nbuff-0.1.14/nbuff/source/nbuff/buffer.d(74,25): Deprecation: `catch` statement without an exception specification is deprecated
../../../../.dub/packages/nbuff-0.1.14/nbuff/source/nbuff/buffer.d(74,25):        use `catch(Throwable)` for old behavior
'-sse4.2' is not a recognized feature for this target (ignoring feature)
SSE: false
Linking...
ld: warning: pointer not aligned at address 0x1003B8F8A (anon + 3978 from .dub/build/application-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-77FB443282C3B47E8927768ABF3DF67B/httpserver.o)
ld: warning: pointer not aligned at address 0x1003C66A9 (anon + 6099 from ../../.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-4AE73981F2F4E335B510885DE12D3FB4/libarchttp.a(archttp.Archttp.o))
ld: warning: pointer not aligned at address 0x1003F2311 (anon + 367 from ../../.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-4AE73981F2F4E335B510885DE12D3FB4/libarchttp.a(archttp.Cookie.o))
ld: warning: pointer not aligned at address 0x1003F31D9 (anon + 388 from ../../.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-4AE73981F2F4E335B510885DE12D3FB4/libarchttp.a(archttp.HttpMessageParser.o))
ld: warning: pointer not aligned at address 0x1003F5839 (anon + 70 from ../../.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-4AE73981F2F4E335B510885DE12D3FB4/libarchttp.a(archttp.HttpMethod.o))
ld: warning: pointer not aligned at address 0x1003F74C1 (anon + 1677 from ../../.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-4AE73981F2F4E335B510885DE12D3FB4/libarchttp.a(archttp.HttpRequestParserHandler.o))
ld: warning: pointer not aligned at address 0x1003F7CFF (anon + 1900 from ../../.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-4AE73981F2F4E335B510885DE12D3FB4/libarchttp.a(archttp.HttpResponse.o))
ld: warning: pointer not aligned at address 0x1003F80FF (anon + 74 from ../../.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-4AE73981F2F4E335B510885DE12D3FB4/libarchttp.a(archttp.HttpStatusCode.o))
ld: warning: pointer not aligned at address 0x1003F8B9A (anon + 69 from ../../.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-4AE73981F2F4E335B510885DE12D3FB4/libarchttp.a(archttp.MultiPart.o))
ld: warning: pointer not aligned at address 0x1003F9447 (anon + 1797 from ../../.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-4AE73981F2F4E335B510885DE12D3FB4/libarchttp.a(archttp.Router.o))
ld: warning: pointer not aligned at address 0x1003FB415 (anon + 1825 from ../../.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-4AE73981F2F4E335B510885DE12D3FB4/libarchttp.a(archttp.codec.HttpCodec.o))
ld: warning: pointer not aligned at address 0x1003FBB6E (anon + 1767 from ../../.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-4AE73981F2F4E335B510885DE12D3FB4/libarchttp.a(archttp.codec.HttpDecoder.o))
ld: warning: pointer not aligned at address 0x1003FC297 (anon + 1691 from ../../.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-4AE73981F2F4E335B510885DE12D3FB4/libarchttp.a(archttp.codec.HttpEncoder.o))
ld: warning: pointer not aligned at address 0x1003FD15B (anon + 3684 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.Exceptions.o))
ld: warning: pointer not aligned at address 0x1004054CA (anon + 4500 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.codec.Codec.o))
ld: warning: pointer not aligned at address 0x10042D171 (anon + 1414 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.codec.Framed.o))
ld: warning: pointer not aligned at address 0x10042D7E2 (anon + 1244 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.event.EventLoop.o))
ld: warning: pointer not aligned at address 0x10042DE1E (anon + 1333 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.event.EventLoopGroup.o))
ld: warning: pointer not aligned at address 0x10042F3F2 (anon + 1226 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.event.selector.Selector.o))
ld: warning: pointer not aligned at address 0x10042FBAB (anon + 1114 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.event.timer.Common.o))
ld: warning: pointer not aligned at address 0x100430A45 (anon + 1366 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.logging.ConsoleLogger.o))
ld: warning: pointer not aligned at address 0x10043E31A (anon + 163 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.logging.Helper.o))
ld: warning: pointer not aligned at address 0x100443636 (anon + 160 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.net.IoError.o))
ld: warning: pointer not aligned at address 0x100443C32 (anon + 1482 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.net.TcpListener.o))
ld: warning: pointer not aligned at address 0x100444532 (anon + 1394 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.net.TcpStream.o))
ld: warning: pointer not aligned at address 0x100444CA9 (anon + 226 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.net.TcpStreamOptions.o))
ld: warning: pointer not aligned at address 0x1004451FB (anon + 1297 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.net.channel.AbstractChannel.o))
ld: warning: pointer not aligned at address 0x100445962 (anon + 1260 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.net.channel.AbstractSocketChannel.o))
ld: warning: pointer not aligned at address 0x100445CFE (anon + 371 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.net.channel.ChannelTask.o))
ld: warning: pointer not aligned at address 0x100445E99 (anon + 226 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.net.channel.Types.o))
ld: warning: pointer not aligned at address 0x100446A0F (anon + 1157 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.net.channel.posix.AbstractListener.o))
ld: warning: pointer not aligned at address 0x10044703F (anon + 1426 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.net.channel.posix.AbstractStream.o))
ld: warning: pointer not aligned at address 0x1004479EF (anon + 1132 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.net.channel.posix.KqueueEventChannel.o))
ld: warning: pointer not aligned at address 0x100447B3B (anon + 105 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.system.Error.o))
ld: warning: pointer not aligned at address 0x100447C61 (anon + 235 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.system.Memory.o))
ld: warning: pointer not aligned at address 0x100447FC5 (anon + 623 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.util.Configuration.o))
ld: warning: pointer not aligned at address 0x10044951B (anon + 353 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.util.Lifecycle.o))
ld: warning: pointer not aligned at address 0x1004496E7 (anon + 185 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.util.ResoureManager.o))
ld: warning: pointer not aligned at address 0x10044A769 (anon + 184 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.util.ThreadHelper.o))
ld: warning: pointer not aligned at address 0x10044BCF1 (anon + 412 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.util.worker.Task.o))
ld: warning: pointer not aligned at address 0x10044C38F (anon + 990 from ../../../../.dub/packages/geario-0.0.1/geario/.dub/build/library-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-BE6C9AA5950D804A5C83DF1502425BEE/libgeario.a(geario.util.worker.Worker.o))
ld: warning: pointer not aligned at address 0x10044DA27 (anon + 2872 from ../../../../.dub/packages/nbuff-0.1.14/nbuff/.dub/build/std-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-5498AEBDA80ED21E1ED6D89172AA2FEB/libnbuff.a(nbuff.buffer.o))
ld: warning: pointer not aligned at address 0x10045CE71 (anon + 1058 from ../../../../.dub/packages/unit-threaded-0.10.8/unit-threaded/subpackages/property/.dub/build/default-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-F9BFD9BB4B70259F96F48B66A1940F06/libunit-threaded_property.a(unit_threaded.property.o))
ld: warning: pointer not aligned at address 0x10045EA3B (anon + 2697 from ../../../../.dub/packages/unit-threaded-0.10.8/unit-threaded/subpackages/property/.dub/build/default-debug-posix.osx.darwin-aarch64.arm_hardfloat-ldc_v1.30.0-beta1-F9BFD9BB4B70259F96F48B66A1940F06/libunit-threaded_property.a(unit_threaded.randomized.benchmark.o))
ld: unaligned pointer(s) for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: /usr/bin/cc failed with status: 1
/Users/zoujiaqing/.local/ldc/bin/ldc2 failed with exit code 1.
```

**Comment by kinke** [comment] 2022-05-20 16:15
Duplicate of https://github.com/ldc-developers/ldc/issues/3864.

**Closed by kinke** 2022-05-20 16:15 UTC
