### ISSUE TITLE
ldc2 fails with lazy struct array function argument

### ISSUE THREAD

**Issue by RealDiez** [ldc-developers/ldc#1760] opened 2016-09-14 15:23 UTC
Tracking down a bug where ldc2 SEGVs on one of my larger source files, I narrowed down another bug.

Compiling the following short program fails using ldc newer than 0.16.1 whereas compiling with dmd succeeds.

Removing the `lazy` keyword from the function argument compiles.

```d
// Ubuntu 12.04, 64 bit

// ldc2-0.16.1-linux-x86_64			succeeds

// ldc2-1.1.0-beta2-linux-x86_64	error:
//		Instruction does not dominate all uses!
//		  %o = alloca %object.Object*, align 8
//		  %7 = load %object.Object*, %object.Object** %o
//		LLVM ERROR: Broken function found, compilation aborted!

// ldc2 <this file>.d

public struct MyStruct
{
	public this(TypeInfo_Class value)
	{
	}
}

//public void myfunc(MyStruct[] pars)			// succeeds
public void myfunc(lazy MyStruct[] pars)		// errors
{
}

class MyClass
{
}

int main(string[] args)
{
	Object o = new MyClass();

	myfunc([MyStruct(typeid(o))]);

	return 0;
}

// -- eof --
```

(Thanks for the testcase! Edited the text to better format the code. @JohanEngelen)

**Comment by JohanEngelen** [comment] 2016-09-15 10:11
Looks like a duplicate of #1369 .

Fails with ldc2-1.1.0-beta2-osx-x86_64, but succeeds with current master.

**Closed by JohanEngelen** 2016-09-15 10:11 UTC
