### ISSUE TITLE
lld-link: error: failed to write the output file: permission denied

### ISSUE THREAD

**Issue by top398** [ldc-developers/ldc#3676] opened 2021-02-22 12:49 UTC
When compiling (simple) D program, LDC 1.25.0 show:
lld-link: error: failed to write the output file: permission denied
And no executable generated but xxx.obj. In 1.24.0, no such error.
The OS js Win7 x64, FS is NTFS.

**Comment by kinke** [comment] 2021-02-22 15:24
Duplicate of #3675.

**Closed by kinke** 2021-02-22 15:24 UTC
