### ISSUE TITLE
Issue with opaque struct across modules

### ISSUE THREAD

**Issue by p0nce** [ldc-developers/ldc#3817] opened 2021-08-17 10:39 UTC
We stumble upon the following problem in https://github.com/dkorpel/libsoundio-d/pull/3#issuecomment-900180315 

```d
module a;

extern(C):

struct A;
void foo(A* a);
```

```d
module b;

extern(C):

struct A {}
void foo(A* a) {}
```

When built:

```
$ ldc2 a.d b.d
a.d(6): Error: Function type does not match previously declared function with the same mangled name: `foo`
a.d(6):        Previous IR type: void (%b.A*)
a.d(6):        New IR type:      void (%a.A*)
```

But it works in DMD.

This doesn't create problem when module a and b are in different translation units, but typically will be exposed with `dub --combined`.

What to do?

**Comment by kinke** [comment] 2021-08-17 19:07
This is yet another duplicate of #2782, #1020 etc. - hence closing. ;)

> What to do?

If possible, extract the struct declaration to a separate module and import it from there. `extern(C)` doesn't change the fact that there are multiple unrelated struct types, and that there are conflicting `foo()` functions with different signatures.

**Closed by kinke** 2021-08-17 19:07 UTC

**Comment by dkorpel** [comment] 2021-08-17 19:34
> If possible, extract the struct declaration to a separate module and import it from there. `extern(C)` doesn't change the fact that there are multiple unrelated struct types, and that there are conflicting `foo()` functions with different signatures.

Does this mean DMD accepting this is a bug? The [spec says](https://dlang.org/spec/struct.html#opaque_struct_unions) that opaque structs can be used to implement the [PIMPL idiom](https://en.wikipedia.org/wiki/Opaque_pointer), but in LDC they're useless?

**Comment by kinke** [comment] 2021-08-17 19:37
It boils down to that you cannot declare the same struct in multiple modules in D. So if the implementation of the struct is in another module, then no, the opaque struct and the impl don't refer to the same type.

**Comment by dkorpel** [comment] 2021-08-17 19:40
Does LDC support another way of implementing the PIMPL idiom?

**Comment by kinke** [comment] 2021-08-17 19:46
This has nothing to do with LDC per se, this is a general D restriction, it's just that DMD has much less strict codegen checks and according bugs, though one might argue that this `extern(C[++])` function signatures check of LDC is overshooting at times and hindering some approaches. For a pimpl thing, I'd probably simply use a `void*` instead of `A*`.

**Comment by dkorpel** [comment] 2021-08-17 19:48
I'll figure something out, thanks!

**Comment by kinke** [comment] 2021-08-17 19:52
To make things clearer:
```
import a, b;

void main()
{
    A inst;
    foo(&inst);
}
```
=>
```
c.d(5): Error: struct `a.A` at a.d(5) conflicts with struct `b.A` at b.d(5)
c.d(5): Error: variable `c.main.inst` no definition of struct `A`
```

**Comment by p0nce** [comment] 2021-08-17 21:31
> Does this mean DMD accepting this is a bug?

I think that yes, it's strange to accept it in the first place.
