### ISSUE TITLE
How to use ldc compile for XCode?

### ISSUE THREAD

**Issue by zoujiaqing** [ldc-developers/ldc#2622] opened 2018-03-23 11:47 UTC
Like title :)

I want write D code support iOS device.

**Comment by kinke** [comment] 2018-03-24 17:30
More or less a duplicate of your https://github.com/ldc-developers/ldc/issues/885 (and yes, questions aren't issues and are still better placed in the forum).
AFAIK, @smolt did integrate considerable portions into vanilla LDC and got iOS on ARM almost fully working, but sadly isn't active anymore, so the current iOS state is unknown to me. Cross-compilation should be simpler now with the [ldc-build-runtime tool](https://wiki.dlang.org/Building_LDC_runtime_libraries), but you'll have to search for infos and experiment yourself if interested.

**Closed by kinke** 2018-03-24 17:30 UTC
