### ISSUE TITLE
skipping definition of function caused by fullyQualifiedName

### ISSUE THREAD

**Issue by MrSmith33** [ldc-developers/ldc#3344] opened 2020-03-03 14:51 UTC
`..\import\std\traits.d(730,19): Warning: skipping definition of function std.traits.fqnSym!(regex).adjustIdent due to previous definition for the same mangled name: _D3std6traits__T6fqnSymSQw5regexZ11adjustIdentFAyaZQe
`

version is ldc 1.20.0
win64

**Comment by kinke** [comment] 2020-03-03 16:48
Please add a reproducible testcase.

**Comment by MrSmith33** [comment] 2020-03-03 21:44
test case:
```D
import std;
void func() {
	Captures!string obj;
	typeId(obj);
	typeId(__traits(getMember, obj, "matches"));
}

auto typeId(T)(T value) {
	auto fqn = fullyQualifiedName!T;
}
```
compiled with `ldc2 -w -c test.d`

**Comment by kinke** [comment] 2020-03-04 00:45
Confirmed, thx. Just to clarify: this is caused by a bad AST, containing multiple definitions for a particular  mangled D function name. I bet it's a problem with DMD as well, just that it doesn't warn about it.

**Comment by JohanEngelen** [comment] 2020-03-04 06:40
related: https://github.com/ldc-developers/ldc/pull/2754

**Comment by kinke** [comment] 2021-09-23 22:17
The testcase works with recent LDC versions and I was able to get rid of according workarounds in Symmetry's codebase. I assume the underlying issue was fixed in the frontend (or Phobos) in the meantime => closing.

**Closed by kinke** 2021-09-23 22:17 UTC
