### ISSUE TITLE
ICE with extern main

### ISSUE THREAD

**Issue by japplegame** [ldc-developers/ldc#3077] opened 2019-05-23 13:09 UTC
This code causes crash:
```d
// test.d
void main();
void foo() {
    main();
}
```
```sh
$ ldc2 -c test.d
...
Segmentation fault (core dumped)
```
With `-betterC` switch also crashes this code:
```d
// test.d
extern(C) void main();
void foo() {
    main();
}
```
```sh
$ ldc2 -c -betterC test.d
...
Aborted (core dumped)
```

LDC version:
```sh
$ ldc2 --version
LDC - the LLVM D compiler (1.15.0):
  based on DMD v2.085.1 and LLVM 8.0.0
  built with LDC - the LLVM D compiler (1.15.0)
  Default target: x86_64-unknown-linux-gnu
```

**Comment by thewilsonator** [comment] 2019-05-23 13:12
That is known. `void main` gets rewritten to `int main(string[])` which violates an assertion somewhere in ldc. Solveable by not using a void main.

**Comment by japplegame** [comment] 2019-05-23 13:12
DMD doesn't have this issue.

**Comment by thewilsonator** [comment] 2019-05-23 13:14
I know. DMD is much less strict about the sanity of its internal state.

**Comment by japplegame** [comment] 2019-05-23 13:16
> That is known. `void main` gets rewritten to `int main(string[])` which violates an assertion somewhere in ldc. Solveable by not using a void main.

Thanks for workaround, but ICE needs to be fixed.

**Comment by kinke** [comment] 2019-05-23 18:28
Closing as perfect duplicate of https://github.com/ldc-developers/ldc/issues/2151.

**Closed by kinke** 2019-05-23 18:28 UTC
