### ISSUE TITLE
crush on building memutils

### ISSUE THREAD

**Issue by bubnenkoff** [ldc-developers/ldc#1708] opened 2016-08-18 17:20 UTC
I am buildng project and one of packages is depend on memutils. On building it LDC2 ( LDC 1.1.0-beta2 ) crush:
http://img.ctrlv.in/img/16/08/18/57b5b7f2aeab3.png

**Comment by kinke** [comment] 2016-08-18 17:55
Thanks for the report; it looks like a Windows Unicode issue. We normally ask you guys to provide a self-contained, minimalistic testcase, so that we LDC guys can immediately get to work. So screenshots, `dub` packages etc. aren't very motivating (I've never used `dub` myself... ;)). And in your particular case, I'm not sure whether I can reproduce it with my English Windows.
So it'd be great if you could put a little more effort into this and do a little pre-analysis (What file causes the issue? Can the relevant code be minimized? ...). Our [Windows CI release](https://github.com/ldc-developers/ldc/releases/tag/LDC-Win64-master) has debuginfos (and enabled assertions), so that could help if you're willing to attach a debugger to LDC once you figured out which file causes the crash.

**Comment by bubnenkoff** [comment] 2016-08-19 09:56
OK!

Fore reproducing you should add next dependency to dub:
```
	"dependencies": 
	{
		"memutils": "==0.4.5"
	}
```


and then:
```
> dub --compiler=ldc2
Performing "debug" build using ldc2 for x86.
memutils 0.4.5: building configuration "secure"...
Enhanced memory security is enabled.
Error: 0x7506D193 (0x0028F86C 0x023C05F9 0x00000000 0x0028F9D4), _wtoi() + 0x970 bytes(s)
0x7506D220 (0x0C6D8158 0x00000080 0x023C05F9 0x00000000), _vsnprintf_l() + 0x56 bytes(s)
0x7506D1C0 (0x0C6D8158 0x00000080 0x023C05F9 0x0028F9D4), vsnprintf() + 0x18 bytes(s)
0x004C2BC9 (0x023C05F9 0x0028F9D4 0x0028F918 0x0209A731)
0x0047C8F5 (0x00000000 0x00000000 0x00000000 0x00000000)
0x0047C9A9 (0x00000000 0x00000000 0x00000000 0x00000000)
0x0047C6B2 (0x00000000 0x00000000 0x00000000 0x00000000)
0x00408033 (0x06EE0908 0x0028FDC8 0x0490D098 0x00000000)
0x0040F333 (0x02E01C08 0x00000059 0x00000002 0x004013DE)
0x004013DE (0x7EFDE000 0x0028FFD4 0x7770A242 0x7EFDE000)
0x76FB338A (0x7EFDE000 0x6233EDBE 0x00000000 0x00000000), BaseThreadInitThunk() + 0x12 bytes(s)
0x7770A242 (0x004014E0 0x7EFDE000 0x00000000 0x00000000), RtlInitializeExceptionChain() + 0x63 bytes(s)
0x7770A215 (0x004014E0 0x7EFDE000 0x00000000 0x78746341), RtlInitializeExceptionChain() + 0x36 bytes(s)
ldc2 failed with exit code -1073741819.
```

**Comment by kinke** [comment] 2016-08-20 13:32
You missed my point. Please re-read what I wrote.

**Comment by kinke** [comment] 2018-05-12 23:40
Closing. FWIW, memutils 0.4.10 compiles fine on Win64 with LDC 1.9.

**Closed by kinke** 2018-05-12 23:40 UTC
Labels: A-information-pending
