### ISSUE TITLE
llvm 18

### ISSUE THREAD

**Issue by calvin2021y** [ldc-developers/ldc#4581] opened 2024-02-14 06:22 UTC

**Comment by calvin2021y** [comment] 2024-02-14 06:24
llvm 18 will released soon, please consider add llvm 18 support.   just try llvm18 build c/c++ projects,  some bugs get fixed compare to llvm 17.0.6.

**Comment by kubo39** [comment] 2024-03-06 13:56
LLVM 18.1.0 has been released. https://releases.llvm.org/18.1.0/docs/ReleaseNotes.html
Note that LLVM changed versioning scheme: https://www.phoronix.com/news/LLVM-N-1-Stable-Versioning

**Comment by liushuyu** [comment] 2024-03-24 22:37
Will be fixed by #4599

**Comment by kubo39** [comment] 2024-03-28 13:27
Can we close this?

**Comment by kinke** [comment] 2024-03-28 15:49
Nope, there are still a few test errors to iron out.

**Comment by kinke** [comment] 2024-05-10 21:21
The results on macOS arm64 are a bit worrying, not sure if that's caused by Xcode v15 though. Looking in good shape on all other tested platforms though, incl. Linux AArch64.

**Closed by kinke** 2024-05-10 21:21 UTC
