### ISSUE TITLE
Different function linkage type in object file for DMD vs. LDC

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#1310] opened 2016-02-21 19:28 UTC
This concerns Windows, I did not check the other OS'es.

``` D
extern (C++) class Expression : RootObject
{
public:
//...
    final Expression optimize(int result, bool keepLvalue = false)
    {
        return Expression_optimize(this, result, keepLvalue);
    }
//...
}
```

When compiled with DMD2.069.2, and running dumpbin, the `Expression::optimize` symbol is put in a section with `selection    2 (pick any)`:

```
1EE 00000000 SECTF8 notype       Static       | .text
    Section length   13, #relocs    1, #linenums    0, checksum        0, selection    2 (pick any)
```

When compiled with LDC0.17, running dumpbin, the `Expression::optimize` symbol is put in a section with `selection 1 (pick no duplicates)`:

```
0AE 00000000 SECT3D notype       Static       | .text
    Section length    6, #relocs    1, #linenums    0, checksum        0, selection    1 (pick no duplicates)
```

The difference in linkage properties shows up in trying to build LDC (with DDMD front-end) using LDC as compiler. Because the C++ source contains a second implementation of `Expression::optimize` as inlined member function:

``` C++
class Expression : public RootObject
{
public:
//...
    Expression *optimize(int result, bool keepLvalue = false)
    {
        return Expression_optimize(this, result, keepLvalue);
    }
```

This then results in a linker error (LNK2005) of multiple defined symbols.

I don't know which compiler is correct: DMD or LDC.

If this needs fixing in LDC, LDC can be made to output all functions in `selection    2 (pick any)` sections by putting the functions in comdat sections: 

``` diff
LinkageWithCOMDAT DtoLinkage(Dsymbol *sym) {
  if (DtoIsTemplateInstance(sym)) {
    return LinkageWithCOMDAT(templateLinkage, supportsCOMDAT());
  }
-  return LinkageWithCOMDAT(llvm::GlobalValue::ExternalLinkage, false);
+  return LinkageWithCOMDAT(llvm::GlobalValue::ExternalLinkage, true);
}
```

**Comment by kinke** [comment] 2016-02-21 19:38
Oh nice that you found the location to be fixed, this is also the reason for a dmd-testsuite failure on Win64. It's just unclear to me as to why that is no problem for all other platforms.

**Comment by JohanEngelen** [comment] 2016-02-21 19:49
Yeah, probably changing the linkage for all functions is not good and not needed.
I am also not sure if what DDMD source is doing (a C++ implementation and a D version) is "legal".

**Comment by JohanEngelen** [comment] 2016-02-22 14:11
Possibly the same root cause (after fixing the above linker problems):
```
druntime-ldc.lib(winsock2.obj) : error LNK2005: htons already defined in ws2_32.lib(WS2_32.dll)
druntime-ldc.lib(winsock2.obj) : error LNK2005: htonl already defined in ws2_32.lib(WS2_32.dll)
druntime-ldc.lib(winsock2.obj) : error LNK2005: ntohs already defined in ws2_32.lib(WS2_32.dll)
druntime-ldc.lib(winsock2.obj) : error LNK2005: ntohl already defined in ws2_32.lib(WS2_32.dll)
```

**Comment by rainers** [comment] 2016-03-20 10:27
>-  return LinkageWithCOMDAT(llvm::GlobalValue::ExternalLinkage, false);
>+  return LinkageWithCOMDAT(llvm::GlobalValue::ExternalLinkage, true);

I looked into this and noticed that the trouble is that -ffunction-sections is enabled, but the selection in TargetLoweringObjectFileCOFF::SelectSectionForGlobal defaults to "no duplicates". This overrides it to "any".

>Yeah, probably changing the linkage for all functions is not good and not needed.

This is actually done by enabling -ffunction-sections and -fdata-sections anyway, but with default selection. Not allowing different code seems problematic when considering linking against libraries compiled with other command line options, but instantiating the same templates.

AFAICT dmd also does just that (emitting all functions as COMDATs) and it is considered a feature to reduce image size.

**Comment by rainers** [comment] 2016-03-20 10:34
> It's just unclear to me as to why that is no problem for all other platforms.

I suspect that ELF doesn't support these selection attributes and always uses any (https://docs.oracle.com/cd/E23824_01/html/819-0690/chapter7-11598.html#scrolltoc). Mach-o doesn't seem to support COMDATs to begin with (not sure how this is implemented).

**Comment by kinke** [comment] 2016-03-28 10:39
Thanks Rainer for the details. We now default to COMDATs as well, so I'm closing this.

**Comment by JohanEngelen** [comment] 2016-03-29 14:53
Are we sure this was correct? This seems very wrong to me now. We now allow this to compile and link on Windows:

```D
// file1.d
int foo() {
    return 1;
}
void main() {
    return;
}
```

```D
// file1.d
int foo() {
    return 2;
}
```

`ldc2 file1.d file2.d`

DMD does allow this, but to me this seems very broken.
I recently added @(ldc.attributes.weak) is someone wants a function to be overridable, but I believe it is a hardcore option for people who are aware of what they are doing. For templates, LLVM has the linkonce_odr attributes and others, such that indeed they don't result in linker errors when templates are instantiated in multiple object files. But to do the "link any" behavior for just any function is bad I think.

**Comment by JohanEngelen** [comment] 2016-03-29 15:02
The above code indeed links with DMD also on Mac, but not with LDC.

**Comment by smolt** [comment] 2016-03-29 15:02
Don't these end up as `file1.foo` and `file2.foo`, two distinct modules?  Or is this something missing your example?

**Comment by JohanEngelen** [comment] 2016-03-29 15:03
@smolt Something missing in my example: "extern(C)" , I've updated my previous comment

**Comment by smolt** [comment] 2016-03-29 15:03
Excuse my early morning grammar!

**Comment by smolt** [comment] 2016-03-29 15:04
Yes, then I agree that is not good behavior.

**Comment by JohanEngelen** [comment] 2016-03-29 15:05
Shall I work on a revert of #1367 ?

**Comment by kinke** [comment] 2016-03-29 18:16
> Shall I work on a revert of #1367 ?

Nope, imho there's way more important stuff than this. Iain (@ibuclaw) dislikes this weak-linking-by-default behavior too. Me too, but there are multiple tests which depend on this DMD-compatible behavior and so would fail again (only for MSVC targets).
And I mean DMD goes way further than this by even allowing different function signatures for `extern(C)`/`extern(Windows)` function declarations, see https://github.com/D-Programming-Language/druntime/pull/1518.
If this is a big issue, it's better fixed upstream.

**Comment by JohanEngelen** [comment] 2016-03-29 18:27
DMD incorrectly accepts extern(C) overrides, see: https://issues.dlang.org/show_bug.cgi?id=15217
This always-weak thing cannot be fixed upstream, or do you mean the testcases?

I'll locally revert (part of) #1367 and see which MSVC tests fail.

**Comment by kinke** [comment] 2016-03-29 19:32
I don't get why you'd care about something noone complained about yet. If you have some spare time, investing it in something like https://github.com/ldc-developers/ldc/issues/1327#issuecomment-202100556 would make much more sense imho.

**Comment by JohanEngelen** [comment] 2016-03-29 19:44
I found out about it because PGO now no longer works on Windows and I do not know the workaround (perhaps there isn't any).

It is very scary compiler behavior I find. Linking order is not a thing for the comdat "any" selection, LLVM says the choice is arbitrary. It's also called "vague linkage". DMD uses this on Windows to override the memory allocation functions, which to me seems to work "by chance" as the COMDAT "any" selection does not guarantee one definition overriding the other...

Just now I found out that weak linkage is not possible on Windows.
https://sourceware.org/ml/binutils/2009-04/msg00133.html
The tests were succeeding because of everything being "vaguely" linked. So I will have to disable @weak on Windows.

**Comment by rainers** [comment] 2016-03-29 20:37
> It is very scary compiler behavior I find. Linking order is not a thing for the comdat "any" selection, LLVM says the choice is arbitrary. It's also called "vague linkage". DMD uses this on Windows to override the memory allocation functions, which to me seems to work "by chance" as the COMDAT "any" selection does not guarantee one definition overriding the other...

It works in DMD because the override is in an object file passed to the linker while the other implementation is in a library. The linker will always prefer the version in the object file.

Even with "no duplicate" selection, you can have different versions of the function in different libraries and really can't tell which implementation is chosen (without warning or error).

**Comment by JohanEngelen** [comment] 2016-03-29 23:32
Thanks @rainers for the extra information. So if I understand correctly, the possibility of errors is small, because it'd be strange for the user to link two "competing" functions in object files.
What shall I do with @weak on Windows? Remove it, or keep it where it would just not do anything different from normal symbols? (if we keep it, code using @weak will not need to be tailored to Windows)

> Even with "no duplicate" selection, you can have different versions of the function in different libraries and really can't tell which implementation is chosen (without warning or error).

So the linking order doesn't matter for comdat sections? (I thought symbols were resolved in the cmdline order of the linked libraries)

**Comment by JohanEngelen** [comment] 2016-03-29 23:34
> it'd be strange for the user to link two "competing" functions in object files.

This is what I was doing in testing and got very weird behavior. But I guess it wouldn't occur like that in practical situations then.

**Comment by rainers** [comment] 2016-03-30 06:18
> So the linking order doesn't matter for comdat sections? (I thought symbols were resolved in the cmdline order of the linked libraries)

I've never seen a definite spec how the symbols are searched. You can specify libraries on the command line and by adding pragma(lib) to the source. Answers at http://stackoverflow.com/questions/2765403/visual-studio-2010-library-linking-order also suggests that the process is rather brittle.

**Comment by JohanEngelen** [comment] 2016-03-30 07:46
Yeah, documentation is scarce :(

**Comment by JohanEngelen** [comment] 2016-04-02 14:08
> What shall I do with @weak on Windows? Remove it, or keep it where it would just not do anything different from normal symbols? 

I now believe that `@weak` still does something useful on Windows: it tells LLVM that inlining of that function is not allowed.

I am trying to get PGO to work again on Windows, and am trying to figure out if the problem is a bug in LLVM or in LDC PGO code. Perhaps LLVM's PGO instrumentation helper functions do not expect a symbol with "external" linkage (the default) to also be in a comdat "any" group. If we put a symbol in a comdat "any" group, I now think that that corresponds more with `linkonce_odr` linkage, instead of `external` linkage. Is that correct?
(if I make that change for Windows, LLVM does not error on the PGO pass any more; only tested it with mtriple=x86_64-pc-windows, haven't tested on Windows itself)

**Comment by JohanEngelen** [comment] 2016-04-03 18:29
I had a short email discussion with David Li (LLVM dev working on PGO) and he also thinks linkonce_odr is correct if we put symbols in comdat "any" groups.

**Comment by Hardcode84** [comment] 2018-01-26 19:03
This COMDAT behavior still cause issues with IR-based instrumentation.
Adding reproduce steps with current llvm and ldc (6.0 and 1.7.0)

main.d
```
int foo()
{
  return 42;
}
```
ldc2 main -output-ll
```
; ModuleID = 'main.d'
source_filename = "main.d"
target datalayout = "e-m:w-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

%0 = type { i32, i32, [5 x i8] }
%object.ModuleInfo = type { i32, i32 }

$_D4main3fooFZi = comdat any

$_D4main12__ModuleInfoZ = comdat any

@_D4main12__ModuleInfoZ = global %0 { i32 -2147483644, i32 0, [5 x i8] c"main\00" }, comdat ; [#uses = 1]
@_D4main11__moduleRefZ = linkonce_odr global %object.ModuleInfo* bitcast (%0* @_D4main12__ModuleInfoZ to %object.ModuleInfo*), section ".minfo" ; [#uses = 1]
@llvm.used = appending global [1 x i8*] [i8* bitcast (%object.ModuleInfo** @_D4main11__moduleRefZ to i8*)], section "llvm.metadata" ; [#uses = 0]

; [#uses = 0]
; Function Attrs: uwtable
define i32 @_D4main3fooFZi() #0 comdat {
  ret i32 42
}

attributes #0 = { uwtable "less-precise-fpmad"="false" "no-frame-pointer-elim"="true" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "target-cpu"="x86-64" "target-features"="+cx16" "unsafe-fp-math"="false" }

!llvm.linker.options = !{}
!llvm.ident = !{!0}

!0 = !{!"ldc version 1.7.0git-43c02ce-dirty"}

```
opt -pgo-instr-gen -instrprof -verify main.ll -S
```
comdat global value has private linkage
[1 x i64]* @__profc__D4main3fooFZi
LLVM ERROR: Broken module found, compilation aborted!
```

Error go away if we remove comdat from `foo`.

**Comment by kinke** [comment] 2018-01-26 19:10
Well this seems to be more of an LLVM bug, as we don't emit that private global ourselves. If it inherits the comdatness from the original symbol, that's fine, but it must most likely be global then to make any sense.

**Comment by Hardcode84** [comment] 2018-01-26 19:18
@kinke Regardless of llvm bug this is still strange and dangerous behavior. Maybe better to keep this open as reminder?

**Comment by kinke** [comment] 2018-01-26 19:22
This issue was about differences between DMD and LDC, and LDC was changed to conform with DMD and its testsuite. You can open a new issue with proper description if you think it's worth it.

**Closed by kinke** 2018-01-26 19:22 UTC
