### ISSUE TITLE
--run option doesn't seem to work as advertised

### ISSUE THREAD

**Issue by baryluk** [ldc-developers/ldc#3719] opened 2021-05-12 17:10 UTC
I have ldc 1.24.0 from Debian testing, on amd64 system.

both --help and man page says:

```
USAGE: ldc2 [options] files --run Runs the resulting program, passing the remaining arguments to it
```

```
       USAGE: ldc [options] files --run program args...
```

But it doesn't work and is either silently ignored or misinterpreted.

Example:

`m.d`:

```d
void main(string[] args) {
  import std;
  writeln(args);
}
```

Only compiles, doesn't run:

```
$ ldc2 m.d --run 
$
```

Doesn't interpret remaining arguments as remaining arguments.

```
$ ldc2 m.d --run  foo
Error: module foo is in file 'foo.d' which cannot be read
import path[0] = /usr/lib/ldc/x86_64-linux-gnu/include/d
import path[1] = /usr/include/d
```

The option `-run` works, but it doesn't seem it is possible to pass extra parameters to the program. I want to use that in `#!` scripts.

And it is order dependent:

```
$ ldc2 m.d -run 
$

$ ldc2 -run m.d 
["/tmp/m-7e64b2b-83679b"]
$ 
```

This undocumented form, appears to work:

```
$ ldc2 -run m.d foo
["/tmp/m-02b25dd-dcffde", "foo"]
```

**Comment by kinke** [comment] 2021-05-17 09:48
This is a limitation of the LLVM CLI API AFAIK, not allowing for a better documentation of this exotic switch. The ldmd2 help is clearer in this regard.

**Comment by kinke** [comment] 2021-06-26 23:47
This is actually a duplicate of long-standing #593.

**Closed by kinke** 2021-06-26 23:47 UTC
