### ISSUE TITLE
extern(C++, "string") causes IR error in ldc 1.14.0 if declared twice

### ISSUE THREAD

**Issue by atilaneves** [ldc-developers/ldc#3021] opened 2019-03-11 13:48 UTC
The code below compiles and links with dmd but errors out with ldc with the following message:

```
mod1.d(6): Error: Function type does not match previously declared function with the same mangled name: _ZNK2ns9Exception4whatEv
mod1.d(6):        Previous IR type: i8* (%mod2.ns.Exception*)
mod1.d(6):        New IR type:      i8* (%mod1.ns.Exception*)
```

Notice that the types are nearly the same but vary by one character: "mod1" vs "mod2". 

The reason the declarations must show up twice is that this is a reduction of automatically translating a C++ header that is #included by more than user-facing header.

Code:

```c++
// cpp.cpp
namespace ns {
    struct Exception {
        const char* what() const {
            return "foobar";
        }
    };
}

void func() {
    ns::Exception e;
    const auto ret = e.what();
    (void) ret;
}
```

```d
// main.d
void main() { }
```

```d
module mod1; // mod1.d

extern(C++, "ns") {
    struct Exception {
        pragma(mangle, "_ZNK2ns9Exception4whatEv")
        const(char)* what() @nogc nothrow const;
    }
}
```

```d
module mod2;  // mod2.d

extern(C++, "ns") {
    struct Exception {
        pragma(mangle, "_ZNK2ns9Exception4whatEv")
        const(char)* what() @nogc nothrow const;
    }
}
```

**Comment by thewilsonator** [comment] 2019-03-11 14:05
That appears to be an (overzealous) sanity check. It is useful when a declaration and a definition do not match but I think two declarations is not obviously an error, Ill look in to it tomorrow.

**Comment by kinke** [comment] 2019-03-11 14:05
Yet another duplicate of #1020, #2178 and #2782. There is no simple 'fix' for this.

**Comment by kinke** [comment] 2019-03-11 17:18
No worries wrt. not finding the duplicates, it's not trivial. ;)

The problem is that the struct is defined multiple times as distinct separate types, one per D module - with all that entails (init symbols, TypeInfos, vtbl etc.). LDC then additionally has the 'problem' of a strongly typed IR, which shows when these different D modules are compiled to a single IR module/object file - we can't have multiple function declarations with the same mangle, but different IR signatures.

So while the LDC-specific issue wrt. LLVM IR probably needs a solution at some point, declaring structs multiple times in different D modules comes at a general cost. Would creating a (single) separate D module for each C(++) header be an option for dpp?

**Comment by kinke** [comment] 2019-03-11 21:50
I think Calypso solved this by conceptually generating a mega-header with all C++ includes (from all .d files) and then generating a single D module for it. Everything's declared just once this way.

**Comment by atilaneves** [comment] 2019-03-13 08:29
> declaring structs multiple times in different D modules comes at a general cost

It doesn't in dmd.

> Would creating a (single) separate D module for each C(++) header be an option for dpp

No:

```d
// dpp1.dpp
#include "hdr1.hpp"
```

```d
/// dpp2.dpp
#include "hdr2.hpp"
```

```c++
// hdr1.hpp
#include "hdr0.hpp"
```

```c++
//hdr2.hpp
#include "hdr0.hpp"
```

```c++
struct Exception { const char* what() const; };
```

Oops.

My "solution" right now is to use dmd instead.

**Comment by kinke** [comment] 2019-03-13 10:28
> It doesn't in dmd.

I don't think so, see TypeInfos, init symbols etc. I mentioned.

Anyway, let's close this, no need for yet another duplicate.

**Closed by kinke** 2019-03-13 10:28 UTC

**Comment by atilaneves** [comment] 2019-03-13 11:12
> I don't think so, see TypeInfos, init symbols etc. I mentioned.

For `extern(C++)`??

**Comment by kinke** [comment] 2019-03-13 11:18
Yes: https://run.dlang.io/is/XsyEYQ

I forgot that with 2.085 we have a new global for each aggregate, `object.RTInfo`.

**Comment by kinke** [comment] 2019-03-14 00:02
Even when not caring about code bloat and compilation speed, multiple equivalent types quickly reach a practical limitation:

a.d:
```
extern(C++, "ns") struct S {}
import b : bar;
void foo(S s) { bar(s); }
```

b.d:
```
extern(C++, "ns") struct S {}
void bar(S s) {}
```

dmd -c a.d:
```
a.d(3): Error: function b.bar(S s) is not callable using argument types (S)
a.d(3):        cannot pass argument s of type a.ns.S to parameter b.ns.S s
```

**Comment by atilaneves** [comment] 2019-03-14 10:34
@kinke A cast would resolve that.
