### ISSUE TITLE
0.17.0-beta2: Cannot build DCD

### ISSUE THREAD

**Issue by Hackerpilot** [ldc-developers/ldc#1266] opened 2016-01-29 04:07 UTC
To reproduce:
```
git clone https://github.com/Hackerpilot/DCD.git
cd DCD
git submodule update --init --recursive
make ldc
```

Error message:
```
ldc2: /home/alaran/src/ldc/ir/irtype.cpp:28: IrType::IrType(Type*, llvm::Type*): Assertion `!dt->ctype && "already has IrType"' failed.
#0 0x7f2ab6b31c97 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/lib64/libLLVMSupport.so.3.7+0xbbc97)
#1 0x7f2ab6b31201 (/usr/lib64/libLLVMSupport.so.3.7+0xbb201)
#2 0x7f2abe7f1d70 __restore_rt (/lib64/libpthread.so.0+0x10d70)
#3 0x7f2ab5e76497 gsignal (/lib64/libc.so.6+0x33497)
#4 0x7f2ab5e778ea abort (/lib64/libc.so.6+0x348ea)
#5 0x7f2ab5e6f3dd (/lib64/libc.so.6+0x2c3dd)
#6 0x7f2ab5e6f492 (/lib64/libc.so.6+0x2c492)
#7 0x806860 IrType::IrType(Type*, llvm::Type*) (/usr/local/bin/ldc2+0x806860)
#8 0x806cfc IrTypeSArray::IrTypeSArray(Type*) (/usr/local/bin/ldc2+0x806cfc)
#9 0x806d37 IrTypeSArray::get(Type*) (/usr/local/bin/ldc2+0x806d37)
#10 0x7a19a9 DtoType(Type*) (/usr/local/bin/ldc2+0x7a19a9)
#11 0x7a1d60 DtoMemType(Type*) (/usr/local/bin/ldc2+0x7a1d60)
#12 0x80898c AggrTypeBuilder::addAggregate(AggregateDeclaration*) (/usr/local/bin/ldc2+0x80898c)
#13 0x811952 IrTypeStruct::get(StructDeclaration*) (/usr/local/bin/ldc2+0x811952)
#14 0x7a1ae1 DtoType(Type*) (/usr/local/bin/ldc2+0x7a1ae1)
#15 0x7a1d60 DtoMemType(Type*) (/usr/local/bin/ldc2+0x7a1d60)
#16 0x806c48 IrTypePointer::get(Type*) (/usr/local/bin/ldc2+0x806c48)
#17 0x7a1963 DtoType(Type*) (/usr/local/bin/ldc2+0x7a1963)
#18 0x7a1d60 DtoMemType(Type*) (/usr/local/bin/ldc2+0x7a1d60)
#19 0x80898c AggrTypeBuilder::addAggregate(AggregateDeclaration*) (/usr/local/bin/ldc2+0x80898c)
#20 0x811952 IrTypeStruct::get(StructDeclaration*) (/usr/local/bin/ldc2+0x811952)
#21 0x7a1ae1 DtoType(Type*) (/usr/local/bin/ldc2+0x7a1ae1)
#22 0x7a1d60 DtoMemType(Type*) (/usr/local/bin/ldc2+0x7a1d60)
#23 0x80898c AggrTypeBuilder::addAggregate(AggregateDeclaration*) (/usr/local/bin/ldc2+0x80898c)
#24 0x811952 IrTypeStruct::get(StructDeclaration*) (/usr/local/bin/ldc2+0x811952)
#25 0x7a1ae1 DtoType(Type*) (/usr/local/bin/ldc2+0x7a1ae1)
#26 0x7a1d60 DtoMemType(Type*) (/usr/local/bin/ldc2+0x7a1d60)
#27 0x806c48 IrTypePointer::get(Type*) (/usr/local/bin/ldc2+0x806c48)
#28 0x7a1963 DtoType(Type*) (/usr/local/bin/ldc2+0x7a1963)
#29 0x7a1d60 DtoMemType(Type*) (/usr/local/bin/ldc2+0x7a1d60)
#30 0x80898c AggrTypeBuilder::addAggregate(AggregateDeclaration*) (/usr/local/bin/ldc2+0x80898c)
#31 0x813119 IrTypeClass::addBaseClassData(AggrTypeBuilder&, ClassDeclaration*) (/usr/local/bin/ldc2+0x813119)
#32 0x8136a5 IrTypeClass::get(ClassDeclaration*) (/usr/local/bin/ldc2+0x8136a5)
#33 0x7a1c19 DtoType(Type*) (/usr/local/bin/ldc2+0x7a1c19)
#34 0x792b63 DtoResolveClass(ClassDeclaration*) (/usr/local/bin/ldc2+0x792b63)
#35 0x824779 CodegenVisitor::visit(ClassDeclaration*) (/usr/local/bin/ldc2+0x824779)
#36 0x6810b0 ClassDeclaration::accept(Visitor*) (/usr/local/bin/ldc2+0x6810b0)
#37 0x825641 CodegenVisitor::visit(AttribDeclaration*) (/usr/local/bin/ldc2+0x825641)
#38 0x60b9ec Visitor::visit(StorageClassDeclaration*) (/usr/local/bin/ldc2+0x60b9ec)
#39 0x6b1cb4 StorageClassDeclaration::accept(Visitor*) (/usr/local/bin/ldc2+0x6b1cb4)
#40 0x823e1c Declaration_codegen(Dsymbol*) (/usr/local/bin/ldc2+0x823e1c)
#41 0x754277 codegenModule(IRState*, Module*, bool) (/usr/local/bin/ldc2+0x754277)
#42 0x5b1270 ldc::CodeGenerator::emit(Module*) (/usr/local/bin/ldc2+0x5b1270)
#43 0x5c7b22 main (/usr/local/bin/ldc2+0x5c7b22)
#44 0x7f2ab5e63620 __libc_start_main (/lib64/libc.so.6+0x20620)
#45 0x59a519 _start (/usr/local/bin/ldc2+0x59a519)
makefile:150: recipe for target 'objs/dsymbol/src/dsymbol/conversion/first.o' failed
make: *** [objs/dsymbol/src/dsymbol/conversion/first.o] Aborted
```

**Comment by redstar** [comment] 2016-01-30 13:35
Confirmed. I can reproduce the error.

**Comment by redstar** [comment] 2016-01-30 13:43
Replace the last step with `ldc2 -c dsymbol\src\dsymbol\scope_.d -Idsymbol\src -Icontainers\src -Imsgpack-d\src -Icontainers\experimental_allocator\src` to reduce to a single source file.

**Comment by redstar** [comment] 2016-01-30 15:09
The `IrType*` instances should be singletons. But during construction of `IrTypeSArray` a call to `DToMemType()`. Since there is no guard against recursive calls, construction of `IrTypeSArray` is triggered a second time with the identical type. The assertion inside the first `IrTypeSArray` then fails.

**Comment by redstar** [comment] 2016-01-30 15:34
Thanks for the bug report.

**Comment by redstar** [comment] 2016-01-30 17:04
Fixed in master.

**Closed by redstar** 2016-01-30 17:04 UTC
