### ISSUE TITLE
could we have phobos.so in https://github.com/ldc-developers/ldc/releases ? 

### ISSUE THREAD

**Issue by timotheecour** [ldc-developers/ldc#1929] opened 2016-12-19 01:54 UTC
running into so many issues to install ldc on linux (works on OSX):
* doesn't work from source: https://github.com/ldc-developers/ldc/issues/1928
* doesn't work from linuxbrew: https://github.com/ldc-developers/ldc/issues/1729 [works w homebrew on osx]
* no dub package
* sudo apt-get install ldc : E: Unable to locate package ldc

So my last resort is to get ldc from https://github.com/ldc-developers/ldc/releases however I need a shared phobos to build a shared library 

(otherwise i'm getting:
ldc2-1.1.0-beta6-linux-x86_64/bin/../lib/libdruntime-ldc.a(errno.c.o): relocation R_X86_64_PC32 against undefined symbol `__errno_location@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
)

so, could we have phobos.so distributed as well as the static libs?
this would be consistent with dmd2/linux/lib64/libphobos2.so distributed in http://downloads.dlang.org/releases/2.x/2.072.1/dmd.2.072.1.linux.tar.xz

**Comment by kinke** [comment] 2016-12-20 18:35
Closing as duplicate of 2-year old #807.

**Closed by kinke** 2016-12-20 18:35 UTC
