### ISSUE TITLE
Project failing to compile due to undefined identifier

### ISSUE THREAD

**Issue by andrewlalis** [ldc-developers/ldc#4356] opened 2023-03-19 09:46 UTC
https://github.com/andrewlalis/handy-httpd/actions/runs/4459966458/jobs/7832787354

In the above GitHub Actions job, I've just ran my job for the first time with LDC 1.32, and I receive this error:
```
Error: undefined identifier `__builtin_ia32_pcmpestri128`
```

I'm assuming that this is because there was a change from a previous LDC version that removed this identifier, but is there any way to go about fixing this? The issue is in a library that my project depends on.

**Comment by thewilsonator** [comment] 2023-03-19 11:07
This is a duplicate of https://github.com/ldc-developers/ldc/issues/4347 which has been fixed in master, there will be a 1.32.1 release soonish that will contain https://github.com/ldc-developers/ldc/pull/4350 the fix for that.

**Closed by thewilsonator** 2023-03-19 11:07 UTC
