### ISSUE TITLE
LDC 1.13.0 fails to build on 32-bit

### ISSUE THREAD

**Issue by ggardet** [ldc-developers/ldc#2947] opened 2018-12-18 14:31 UTC
The following error is encountered when LDC 0.17.6 is used to bootstrap 1.13.0 on 32-bit systems (seen on x86 and armv7):
```
[  622s] /home/abuild/rpmbuild/BUILD/ldc-1.13.0-src/dmd/builtin.d(254): Error: function core.bitop.bsf (uint v) is not callable using argument types (ulong)
[  622s] /home/abuild/rpmbuild/BUILD/ldc-1.13.0-src/dmd/builtin.d(264): Error: function core.bitop.bsr (uint v) is not callable using argument types (ulong)
```

**Comment by kinke** [comment] 2018-12-18 16:59
Duplicate of https://github.com/ldc-developers/ldc/issues/2926.

**Closed by kinke** 2018-12-18 16:59 UTC

**Comment by ggardet** [comment] 2019-01-21 14:15
My current workaround is to build 0.17.6 => 1.12.0 => current (1.13.0)
