### ISSUE TITLE
double-nested try/finally causes ICE on Windows (but not on Linux)

### ISSUE THREAD

**Issue by brianush1** [ldc-developers/ldc#4552] opened 2024-01-05 17:49 UTC
```d
void foo() {}

void bar() {
        try {
            foo();
        }
        finally {
            try {
                foo();
            }
            finally {
                foo();
            }
        }
}
```

causes LDC to exit with the output

```
Unwind edges out of a funclet pad must have the same unwind dest
  %3 = cleanuppad within none []
  cleanupret from %3 unwind to caller
  invoke x86_vectorcallcc void @"\01_D7example3fooFZv"() #0 [ "funclet"(token %3) ]
          to label %6 unwind label %12
LLVM ERROR: Broken function found, compilation aborted!
Exception Code: 0xC000001D
```

**Comment by brianush1** [comment] 2024-01-05 18:21
I can reproduce the issue on Wine too. Doesn't seem to be an issue on Mac, so probably all posix systems are safe.

**Comment by dnadlinger** [comment] 2024-01-05 18:25
Thanks for the exhaustive tests – this makes sense, as Windows EH codegen is different to DWARF EH. Which version are you testing – the latest release?

**Comment by brianush1** [comment] 2024-01-05 18:26
I've reproduced the issue on my machine on both LDC 1.32.1 and 1.35.0; one person reproduced it on their machine on LDC 1.34.0, and another reproduced it on LDC 1.35.0

**Comment by dnadlinger** [comment] 2024-01-05 18:30
If you wanted to investigate this, the first place to look at would be `gen/trycatchfinally.cpp`, in particular the `useMSVCEH()` conditionals. (It's been a while since I've worked on LDC; just saw this scroll by.)

**Comment by kinke** [comment] 2024-01-05 21:06
Closing as duplicate of #3504.

**Closed by kinke** 2024-01-05 21:06 UTC
