### ISSUE TITLE
Add aarch64 support for 0.17

### ISSUE THREAD

**Issue by kalev** [ldc-developers/ldc#1853] opened 2016-10-25 13:01 UTC
0.17.2 currently fails to build for aarch64 in Fedora rawhide with:

    cd /builddir/build/BUILD/ldc-0.17.2-src && /builddir/build/BUILD/ldc-0.17.2-src/build/bin/ldc2 --output-o -c -I/builddir/build/BUILD/ldc-0.17.2-src/runtime/druntime/src -I/builddir/build/BUILD/ldc-0.17.2-src/runtime/druntime/src/gc /builddir/build/BUILD/ldc-0.17.2-src/runtime/phobos/std/math.d -of/builddir/build/BUILD/ldc-0.17.2-src/build/runtime/std/math-debug.o -w -relocation-model=pic -g -link-debuglib -I/builddir/build/BUILD/ldc-0.17.2-src/runtime/phobos
    /builddir/build/BUILD/ldc-0.17.2-src/runtime/phobos/std/math.d(1705): Error: static assert  "Not implemented for this architecture"

https://kojipkgs.fedoraproject.org//work/tasks/6041/16196041/build.log has the whole build log (short lived link).

Please add aarch64 support to 0.17 so that we can bootstrap ldc in rawhide.

**Comment by kinke** [comment] 2016-10-25 13:54
Afaik, LDC itself doesn't need Phobos (at least as long as https://github.com/ldc-developers/ldc/pull/1832 isn't merged), so that shouldn't be an issue. 128-bit floats still aren't supported in Phobos though, so LDC master wouldn't fully work either. See https://github.com/ldc-developers/ldc/issues/1516. Closing this as duplicate.

**Closed by kinke** 2016-10-25 13:54 UTC

**Comment by JohanEngelen** [comment] 2016-10-25 14:22
> Afaik, LDC itself doesn't need Phobos

LDC does need Phobos: e.g. ddmd/ldcbindings.d and driver/cache_pruning.d

Perhaps we can add something like a `version(LDC_BROKEN_PHOBOS)` that people can use to try and bootstrap with a half-broken Phobos?  When the version is defined, it removes stuff from Phobos that breaks builds and that is not needed for building LDC's D-source.
(so let's reopen?)

**Comment by kinke** [comment] 2016-10-25 15:31
Thanks Johan.

> so let's reopen?

I don't think so, it's really a duplicate of the std.math issue, with the wish to backport that (not really LDC-specific, i.e., GDC could use it too) enhancement to the 0.17 branch.

**Comment by d-random-contributor** [comment] 2016-12-22 14:43
I don't think arm has quad floats. 128-bit SIMD registers are normal SIMD vector registers that can hold 2 doubles or 4 floats.
