### ISSUE TITLE
Can you make a new 0.17.x release?

### ISSUE THREAD

**Issue by orip** [ldc-developers/ldc#2780] opened 2018-07-17 11:04 UTC
ltsmaster supports LLVM 6, but 0.17.5 doesn't.
It would be great to get LLVM 6 support for the homebrew formula but ldc-lts won't build with it. Once there's a release I can update my PR with LLVM 6 support.
They also rejected a binary bootstrap version.

CC: @JohanEngelen 

reference: https://github.com/Homebrew/homebrew-core/pull/30116

**Comment by kinke** [comment] 2018-07-17 11:21
Duplicate of #2663.

[I'd prefer just using the `ltsmaster` branch in the formula.]

**Closed by kinke** 2018-07-17 11:21 UTC
