### ISSUE TITLE
build with -O generate "Bus error: 10"

### ISSUE THREAD

**Issue by patrickkh7788** [ldc-developers/ldc#2888] opened 2018-10-28 14:21 UTC
When build with -O, the code can random run into "Bus error: 10"

remove -O, all work fine. 

this is the lldb report:

thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x100711e88)
    frame #0: 0x0000000100711e88
->  0x100711e88: fildll (%rax,%rax)
    0x100711e8c: addl   %eax, (%rax)
    0x100711e8e: addb   %al, (%rax)
    0x100711e90: sbbb   %bl, (%rdi)

LDC - the LLVM D compiler (1.12.0):
  based on DMD v2.082.1 and LLVM 7.0.0
  built with LDC - the LLVM D compiler (1.12.0)
  Default target: x86_64-apple-darwin17.6.0
  Host CPU: skylake

**Comment by kinke** [comment] 2018-10-28 16:15
This is almost certainly a duplicate of your other issue, just depending on what random garbage address you get. Quoting from https://forums.developer.apple.com/thread/70950:
> The difference between SIGSEGV and SIGBUS is a subtle one.  In the general case there’s very little difference; they both mean that the CPU has taken a memory access exception (this is a machine exception, unrelated to language exceptions like you see in Objective-C, C++ and, if you squint, Swift), and the actual signal you get is both OS and hardware related.
However, on Apple platforms the difference is actually pretty clear.  You get a SIGSEGV when you access unmapped memory and you get a SIGBUS when you access memory that’s mapped but whose protection isn’t compatible with your access.

**Comment by patrickkh7788** [comment] 2018-10-29 01:37
This is my code crashing from macOSX x86, random and not always repeat.

**Comment by joakim-noah** [comment] 2018-10-30 11:01
Sounds like optimization is screwing something up, if it's really not hitting at all on unoptimized builds. These sporadic issues are really hard to track down, best we can offer is that you will have to use lldb to try to get a feel for where in your code it's happening and see if you can produce a minimized testcase.

**Comment by patrickkh7788** [comment] 2018-10-31 06:58
Yes, I only see this error with -O,  I will paste here if I get minimized test case.  

Right now I use it without -O,   the bad side is the binary tree search not near half the performance compare with -O.

**Closed** 2019-03-28 00:54 UTC
