### ISSUE TITLE
LDC crash (errors in basic blocks and others)

### ISSUE THREAD

**Issue by MrSmith33** [ldc-developers/ldc#1720] opened 2016-08-26 10:02 UTC
Here I attach somewhat reduced version of a project with all sources in one directory and no static libs.
Compiled with `dub build --compiler=ldc2 --force`

Errors are in `errors.txt` file. I've got several different outputs and stack traces while reducing the project.

Also, on travis: https://travis-ci.org/MrSmith33/voxelman/jobs/155073583

[voxelman.zip](https://github.com/ldc-developers/ldc/files/438998/voxelman.zip)

**Comment by kinke** [comment] 2016-08-26 12:05
This has got to be a duplicate of https://github.com/ldc-developers/ldc/issues/1638 and should thus be fixed in master.
Closing this. If it still fails with the [latest CI build](https://github.com/ldc-developers/ldc/releases/tag/LDC-Win64-master), please reopen.

**Closed by kinke** 2016-08-26 12:05 UTC

**Comment by MrSmith33** [comment] 2016-08-26 16:08
Yep, it works!
