### ISSUE TITLE
Invalid assembly in 64-bit (regression) 

### ISSUE THREAD

**Issue by p0nce** [ldc-developers/ldc#1944] opened 2016-12-26 00:49 UTC
LDC version: ldc2-1.1.0-beta6-win64-msvc
LLVM 3.9.0

**What I see:**

![image](https://cloud.githubusercontent.com/assets/1067485/21473472/291cdf88-cb0d-11e6-8568-9cab6656a139.png)

**How to reproduce** (`iir.d`)
`ldc2 -c iir.d -march x86-64`
Worths otherwise in 32-bit.

**Input program**
```d

struct Vec(T, int N)
{
    T[N] v;    
    ref T opIndex(size_t i)
    {
        return v[i];
    }

    T opIndexAssign(U : T)(U x, size_t i)
    {
        return v[i] = x;
    }        
}


struct IIRDelay
{
    alias Vec!(double, 2) delay_t;
    alias Vec!(float, 5) coeff_t;

    delay_t x;
    delay_t y;

    void nextBuffer(float* pointer0, float* pointer1, int num, coeff_t coeff)
    {
        double x0 = x[0],
            x1 = x[1],
            y0 = y[0],
            y1 = y[1];

        double a0 = coeff[0],
            a1 = coeff[1],
            a2 = coeff[2],
            a3 = coeff[3],
            a4 = coeff[4];

        ubyte[16*2] storage;

        asm nothrow @nogc
        {
            movups storage+16, XMM7;
            movups XMM7, storage+16;
        }

        x[0] = x0;
        x[1] = x1;
        y[0] = y0;
        y[1] = y1;
    }
}

```

This used to work with LDC 1.0.0-beta2

**Comment by thewilsonator** [comment] 2016-12-26 08:21
Works for me on OSX with recent ldc, but -output-s gives me 
```
	movups	%xmm7, -152(%rbp)
	movups	-152(%rbp), %xmm7
```
as the inline assembly portion.

Could you please try `ldc2 -c iir.d -march x86-64 -vv` and post the interesting bits (most likely the tail portion) of the output.

I take it this _is_ the dustmited version?

**Comment by p0nce** [comment] 2016-12-26 10:04
No this isn't the  dustmited version, it was reduced by hand but it's quite hard to reduce further. It seems to appear depending on the stack alignment.

I'm not sure what are the interesting bits but here is it: http://pastebin.com/8SGUbeF7

**Comment by p0nce** [comment] 2016-12-26 10:21
A bit reduced version:
```d
struct V
{
    double opIndex(size_t i)
    {
        return 0;
    }

    double opIndexAssign(double x, size_t i)
    {
        return 0;
    }
}


struct IIRDelay
{
    V x;
    V y;

    void nextBuffer(float* pointer0, float* pointer1, int num)
    {
        double x0 = 0,
            x1 = x[1],
            y0 = y[0],
            y1 = y[1];

        double a0 = x[0];
        ubyte[32] storage;

        asm
        {
            movups storage+16, XMM7;
            movups XMM7, storage+16;
        }

        x[0] = x0;
        x[1] = x1;
        y[0] = y0;
        y[1] = y1;
    }
}
```

**Comment by thewilsonator** [comment] 2016-12-26 10:30
the relevant bit is 
```
* * * * * CompoundAsmStatement::toIR(): iir.d(39)
* * * * * * AsmStatement::toIR(): iir.d(41)
* * * * * * * AddrExp::toElem: &storage @ ubyte[32]*
* * * * * * * * VarExp::toElem: storage @ ubyte[32]
* * * * * * * * * DtoSymbolAddress ('storage' of type 'ubyte[32]')
* * * * * * * * * * a normal variable
* * * * * * * * is nothing special
* * * * * * * * lval:   %18 = alloca [32 x i8], align 1
* * * * * * * * Building type: ubyte[32]*
* * * * * * * final asm: movups %xmm7, 16+$<<out0>>
* * * * * * * GCC-style output constraints: { =*m }
* * * * * * * GCC-style input constraints: { }
* * * * * * * GCC-style clobbers: { memory }
* * * * * * * Output values:
* * * * * * * * Out 0 =   %18 = alloca [32 x i8], align 1
* * * * * * * Input values:
* * * * * * AsmStatement::toIR(): iir.d(42)
* * * * * * * AddrExp::toElem: &storage @ ubyte[32]*
* * * * * * * * VarExp::toElem: storage @ ubyte[32]
* * * * * * * * * DtoSymbolAddress ('storage' of type 'ubyte[32]')
* * * * * * * * * * a normal variable
* * * * * * * * is nothing special
* * * * * * * * lval:   %18 = alloca [32 x i8], align 1
* * * * * * * final asm: movups 16+$<<in0>>, %xmm7
* * * * * * * GCC-style output constraints: { }
* * * * * * * GCC-style input constraints: { *m }
* * * * * * * GCC-style clobbers: { xmm7 }
* * * * * * * Output values:
* * * * * * * Input values:
* * * * * * * * In  0 =   %18 = alloca [32 x i8], align 1
* * * * * * do outputs
* * * * * * do inputs
* * * * * * code = "movups %xmm7, 16+$0
    movups 16+$1, %xmm7"
* * * * * * constraints = "=*m,*m,~{memory},~{xmm7}"
* * * * * * function type = void ([32 x i8]*, [32 x i8]*)
* * * * * * Arguments:
* * * * * * * $0 ==>   %18 = alloca [32 x i8], align 1* * * * * * * $1 ==>   %18 = alloca [32 x i8], align 1* * * * * * Complete asm statement:   call void asm sideeffect "movups %xmm7, 16+$0\0A\09movups 16+$1, %xmm7", "=*m,*m,~{memory},~{xmm7}"([32 x i8]* %18, [32 x i8]* %18)
```

nothing seems out of place.
The constraints match what I get ("=*m,*m,~{memory},~{xmm7}") and so does the generated asm string ("movups %xmm7, 16+$0\0A\09movups 16+$1, %xmm7")
What does seem weird is that `&storage` ends up as `%rpb` i.e. at the base of the stack frame, when there are other variables declared before it (perhaps a reordering to reduce required padding?).

**Comment by p0nce** [comment] 2016-12-26 10:35
Can't reproduce on Linux x86_64 (ldc2-1.1.0-beta6-linux-x86_64), despite it's the same LLVM version.

**Comment by thewilsonator** [comment] 2016-12-26 10:47
Ooh yeah, what LLVM version are you using? (I always forget to ask that :( )

**Comment by p0nce** [comment] 2016-12-26 17:00
This problems shows with:
```
LDC - the LLVM D compiler (1.1.0-beta6):
  based on DMD v2.071.2 and LLVM 3.9.0
```

**Comment by JohanEngelen** [comment] 2016-12-27 22:26
@p0nce What's the triple that shows the failure (`-output-ll` and look at the first few lines of the LLVM IR)? And can you reproduce it when you specify that triple on Linux?

**Comment by p0nce** [comment] 2016-12-27 22:34
I've tested on Linux 64-bit with the same version and test-case, no bug there.
Here is the output IR: http://pastebin.com/5UTS0ibA
It says `target triple = "x86_64-pc-windows-msvc"`

**Comment by JohanEngelen** [comment] 2016-12-27 22:40
And so this works with 1.1.0-beta2 ?   Comparing the IR may put us on the track to fixing the bug.

**Comment by p0nce** [comment] 2016-12-27 22:45
Here is the output IR (generated on Windows): http://pastebin.com/5UTS0ibA
It says `target triple = "x86_64-pc-windows-msvc"`

I can reproduce on Linux when specifying the same triple.

![image](https://cloud.githubusercontent.com/assets/1067485/21509928/6cfe3bd4-cc8e-11e6-87fd-01ae38d9bea2.png)

However with `-output-ll` it doesn't show the same error messages, terminated without messages.

**Comment by thewilsonator** [comment] 2016-12-27 22:48
In which case (and as suggested by the `-vv` output, with stderr at the end) the error occurs when the backend tries to interpret the assembly.

**Comment by p0nce** [comment] 2016-12-27 22:53
@thewilsonator Makes sense.

Here the IR generated by 1.0.0-b2 and 1.1.0-b6, if that can help.
[repro.zip](https://github.com/ldc-developers/ldc/files/674739/repro.zip)

**Comment by thewilsonator** [comment] 2016-12-27 23:09
[1.diff.txt](https://github.com/ldc-developers/ldc/files/674753/1.diff.txt)
is the diff.

**Comment by JohanEngelen** [comment] 2016-12-27 23:10
Perhaps the extra function attributes (e.g. `attributes #2 = { ... "target-cpu"="x86-64" `) are to blame.

**Comment by thewilsonator** [comment] 2016-12-27 23:16
Would have to be wouldn't it? 
The only other things to have changed are:
* Object/Typeinfo/Module stuff, the removal of uwtable (because not systemV?) and,
* changes to the setup of memset for the zero initialisation of the array.

**Comment by thewilsonator** [comment] 2016-12-27 23:21
Ignoring all the floating point math attributes leaves:
* "no-frame-pointer-elim"="false"
* "target-cpu"="x86-64"
* "target-features"="+cx16"
Dunno what that last one means.

**Comment by p0nce** [comment] 2016-12-27 23:29
[minus-one-line-repro.zip](https://github.com/ldc-developers/ldc/files/674763/minus-one-line-repro.zip)

Using 1.1.0-b6, I generated the IR of the program provoking the asm problem, and another that does not because the line `y[0] = y0;` was removed.

**Comment by thewilsonator** [comment] 2016-12-27 23:37
resulting diff
```
-  %21 = load double, double* %y0                  ; [#uses = 1]
-  %22 = call double @_D3iir1V13opIndexAssignMFdmZd(%iir.V* nonnull %20, i64 0, double %21) #0 ; [#uses = 0]
-  %23 = getelementptr inbounds %iir.IIRDelay, %iir.IIRDelay* %.this_arg, i32 0, i32 1 ; [#uses = 1, type = %iir.V*]
-  %24 = load double, double* %y1                  ; [#uses = 1]
-  %25 = call double @_D3iir1V13opIndexAssignMFdmZd(%iir.V* nonnull %23, i64 1, double %24) #0 ; [#uses = 0]
+  %21 = load double, double* %y1                  ; [#uses = 1]
+  %22 = call double @_D3iir1V13opIndexAssignMFdmZd(%iir.V* nonnull %20, i64 1, double %21) #0 ; [#uses = 0]
```

**Comment by thewilsonator** [comment] 2016-12-27 23:42
That definitely looks like a backend bug to me. All that changes in the above is real just the removal of `y[0] = y0;`. Could you post a diff of the assembly generated for the above case please?

**Comment by p0nce** [comment] 2016-12-28 00:04
Both assembly output with `-output-s` instead
[minus-one-line-asm.zip](https://github.com/ldc-developers/ldc/files/674797/minus-one-line-asm.zip)
The assembly generated in case of the bug is shorter.

**Comment by thewilsonator** [comment] 2016-12-28 00:16
Weird the buggy version contains no `movups` at all!

**Comment by JohanEngelen** [comment] 2016-12-28 21:21
(just a small hint in case you are not aware: you can "dustmite" LLVM IR with LLVM's `bugpoint`)

**Comment by kinke** [comment] 2017-03-29 18:40
I can reproduce it with 1.1.1 and 1.2.0-beta1 (both with LLVM 3.9.1) on Win64, but not with current master and LLVM 4.0 anymore. Might really have been due to the temporary removal of the `uwtable` function attribute, in which case it should be fixed with the next (1.2.0) beta.

**Comment by p0nce** [comment] 2017-03-29 19:00
I use a work-around anyway. You can mark it fixed. Thanks for the awesome work on LDC.

**Comment by kinke** [comment] 2017-10-30 03:04
Definitely working: https://godbolt.org/g/zrRw3M

**Closed by kinke** 2017-10-30 03:04 UTC
