### ISSUE TITLE
Why unittests on LDC goes in reverse order?

### ISSUE THREAD

**Issue by Ewa-D** [ldc-developers/ldc#3516] opened 2020-07-22 15:20 UTC
```
unittest { writeln("unittest1"); }
unittest { writeln("unittest2"); }
unittest { writeln("unittest3"); }
unittest { writeln("unittest4"); }

```
The output will be:
unittest4
unittest3
unittest2
unittest1

**Comment by JohanEngelen** [comment] 2020-07-22 16:46
Please provide a full testcase and what LDC version you are using. It does not reproduce with many different versions of LDC.
https://d.godbolt.org/z/8fTeqc

**Comment by Ewa-D** [comment] 2020-07-22 17:41
at least in all versions after ldc.2.1.21.0

**Comment by kinke** [comment] 2020-07-22 18:35
Well that's some vital piece of information, don't you think? - This most likely also depends on how these different modules are built (single object file vs. separate ones). In the separate case, the order probably depends on the object files order in the linker cmdline, and LDC performing codegen in reverse order (last module in cmdline is the first one being codegen'd) might be the explanation.

**Comment by Ewa-D** [comment] 2020-07-23 06:35
kinke, why are you working here? To close each issue without any changes? Yesterday I created 3 issues with bugs and today 2 issues are removed. And I think this issue also will be removed without any changes in source code.

If you don't want to do your job, then let other developers work instead of you.

**Comment by kinke** [comment] 2020-07-23 06:41
I 'work' here because I love spending my free time for ungrateful idiots like you.

**Comment by FeepingCreature** [comment] 2020-07-23 08:58
> If you don't want to do your job, then let other developers work instead of you.

He ain't stopping you.

How do they say? "Patches welcome." The fork button is on the top right of the main page.

**Comment by Ewa-D** [comment] 2020-07-23 09:05
Nothing is welcome in LDC, kinke is GOD, and all of us is idiots. We must pray on kinke and be happy for great compiler.

**Comment by FeepingCreature** [comment] 2020-07-23 09:13
The thing about Git is that you can genuinely, very easily, make your own ldc. You really just click the fork button, and then you have your own copy of ldc in your own userspace that you can do whatever you want in. You even get your own issues page, where you can file your own issues and kinke can't delete them, if you turn on the box that says "issues" in the fork settings.

**Comment by Ewa-D** [comment] 2020-07-23 09:19
FeepingCreature thank you for like on phrase "idiot"

**Comment by Ewa-D** [comment] 2020-07-23 09:21
I send abuse on both of you.

**Comment by JohanEngelen** [comment] 2020-07-23 09:26
@Ewa-D In this bug report there is simply not enough information to judge what the bug is, and you are not providing any more constructive info --> closing it.

Note that your other two bug reports were not closed by kinke but by me and David. They were simply invalid bug reports. While those may be hard for you to understand, for people who work on the compiler daily those cases are trivial user errors instead of compiler bugs. @kinke is _by far_ the most active contributor at the moment, and what gets frustrating very fast is users writing reports like yours with demands without putting in any effort themselves.
Bug reports are welcome with full details and more if requested, not things like "just divide this code to different modules".

@kinke should not have used "idiot", I'll grant you that. But I share his frustration with your https://github.com/ldc-developers/ldc/issues/3516#issuecomment-662841994

**Closed by JohanEngelen** 2020-07-23 09:26 UTC
