### ISSUE TITLE
GC on Android SIGSEGV

### ISSUE THREAD

**Issue by MartinKrocek** [ldc-developers/ldc#3350] opened 2020-03-07 10:57 UTC
I'm trying to build android NativeActivity application with ldc. And I have strange errors with GC

-mtriple=i686-none-linux-android

```
I/NativeActivity( 2948): _nativeInit
D/NativeActivity( 2948): _jni_nativeInit
D/NativeActivity( 2948): _jni_nativeInit 32 bit
D/NativeActivity( 2948): _android_app_thread
D/NativeActivity( 2948): core.runtime.rt_init
D/NativeActivity( 2948): initSections
D/NativeActivity( 2948): initSections LDC mbeg = 0xa16f96f0, mend = 0xa16faa40
D/NativeActivity( 2948): _jni_nativeInit ok
D/NativeActivity( 2948): initSections LDC pbeg = 0xa16a8a64, pend = 0xb7714658
D/NativeActivity( 2948): initSections LDC pbeg = 0xa16a8a64, pend = 0xb7714658
I/NativeActivity( 2948): _nativeInit ok
I/NativeActivity( 2948): WebViewNativeActivity.onCreate ok
D/NativeActivity( 2948): initTLSRanges

```
here i'm trying to allocate 25 bytes
char[1024] buf;
....
return buf[0 .. len].idup; // len = 25

on idup it crashes

```
D/NativeActivity( 2948): _d_newarrayU(length = x19, size = 1)
D/NativeActivity( 2948): __arrayAlloc size = 25
D/NativeActivity( 2948): __arrayAlloc typeInfoSize = 0
D/NativeActivity( 2948): __arrayAlloc padSize = 1
D/NativeActivity( 2948): __arrayAlloc padded_size = 26
D/NativeActivity( 2948): __arrayAlloc GC.qalloc padded_size = 26
D/NativeActivity( 2948): GC.qalloc sz = 26
D/NativeActivity( 2948): gc/proxy/gc_qalloc sz = 26
D/NativeActivity( 2948): gc/impl/proto/gc qalloc 26
D/NativeActivity( 2948): gc_init()
D/NativeActivity( 2948): gc_init() !isInstanceInit
D/NativeActivity( 2948): createGCInstance conservative
D/NativeActivity( 2948): createGCInstance entry.name = conservative ok
D/NativeActivity( 2948): gc/impl/conservative/gc private GC initialize()
D/NativeActivity( 2948): gc/impl/conservative/gc private GC initialize() 1
D/NativeActivity( 2948): gc/impl/conservative/gc private GC initialize() ok
D/NativeActivity( 2948): 0xb3d93f80.Gcx::addRange(0xa16a8a64, 0xb7714658)
D/NativeActivity( 2948): gc/impl/proto/gc qalloc 26
D/NativeActivity( 2948): gc/proxy/gc_qalloc sz = 26
D/NativeActivity( 2948): conservative/gc/qalloc 26
D/NativeActivity( 2948): GC::malloc(gcx = 0xb3d93f80, size = 26 bits = a, ti = TypeInfo_a)
D/NativeActivity( 2948): Gcx.fullcollect()
D/NativeActivity( 2948): startScanThreads: 1 threads per CPU
D/NativeActivity( 2948): preparing mark.
D/NativeActivity( 2948): 	collect stacks.
D/NativeActivity( 2948): collectRoots
D/NativeActivity( 2948): collectRoots pbot = 0xa0ff4050, ptop = 0xa0ff9000
D/NativeActivity( 2948): collectRoots minAddr = 0x0, memSize = 0
D/NativeActivity( 2948): scanTLSRanges
D/NativeActivity( 2948): collectRoots
D/NativeActivity( 2948): collectRoots pbot = 0xb3fc8100, ptop = 0xb3fc81f8
D/NativeActivity( 2948): collectRoots minAddr = 0x0, memSize = 0
D/NativeActivity( 2948): 	collect roots[]
D/NativeActivity( 2948): 	collect ranges[]
D/NativeActivity( 2948): 		0xa16a8a64 .. 0xb7714658
D/NativeActivity( 2948): collectRoots
D/NativeActivity( 2948): collectRoots pbot = 0xa16a8a64, ptop = 0xb7714658
D/NativeActivity( 2948): collectRoots minAddr = 0x0, memSize = 0
--------- beginning of crash

```

and when I try to run with -mtriple=aarch64-none-linux-android the result is more strange:
the size of memory 25 changed to 26 (it is ok), bun then it changed to 10???, and then  size = -309990416 (in function conservative/gc/qalloc). Why???

```
D/NativeActivity: _d_newarrayU(length = x19, size = 1)
D/NativeActivity: __arrayAlloc size = 25
D/NativeActivity: __arrayAlloc typeInfoSize = 0
D/NativeActivity: __arrayAlloc padSize = 1
D/NativeActivity: __arrayAlloc padded_size = 26
D/NativeActivity: __arrayAlloc GC.qalloc padded_size = 26
D/NativeActivity: GC.qalloc sz = 26
D/NativeActivity: gc/proxy/gc_qalloc sz = 26
D/NativeActivity: gc/impl/proto/gc qalloc 10
D/NativeActivity: gc_init()
D/NativeActivity: gc_init() !isInstanceInit
D/NativeActivity: createGCInstance conservative
D/NativeActivity: createGCInstance entry.name = conservative ok
D/NativeActivity: gc/impl/conservative/gc private GC initialize()
D/NativeActivity: gc/impl/conservative/gc private GC initialize() ok
D/NativeActivity: gc/impl/proto/gc qalloc 10
D/NativeActivity: gc/proxy/gc_qalloc sz = 10
D/NativeActivity: conservative/gc/qalloc -309990416, _add = -320560320

```

With -mtriple=armv7-none-linux-androideabi all works good without errors.

If I turn off the GC by adding in code
`extern(C) pragma(mangle, "rt_options") __gshared string[] rt_options = [ "gcopt=disable:1" ];`
all works good on all android targets.

I test it in Android studio emulator, Android 7.0, API 24

**Comment by kinke** [comment] 2020-03-07 13:11
This should already be fixed in branch `merge-2.091` by https://github.com/ldc-developers/ldc/pull/3332.

**Comment by MartinKrocek** [comment] 2020-03-07 14:24
> Do you have a D main in the first object file fed to the linker?
Yes, see my build script

$HOME/ldc.2.1.20.0.linux/bin/ldc2
    -c
    -of=$PROJECT/obj/android/testapp-aarch64.o
    --d-debug
    -g
    -w
    -I=$FRAMEWORK/src
    -i=framework
    -I=$PROJECT/src
    -i=testapp
    -mtriple=aarch64-none-linux-android
    --d-version=Application
    --d-version=AndroidNativeActivity
    $PROJECT/src/testapp/main.d

$HOME/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
    -o $PROJECT/obj/android/lib/arm64-v8a/libtestapp.so
    -shared
    -Wl,-soname,libtestapp.so
    -fuse-ld=bfd
    -target aarch64-none-linux-android
    -gcc-toolchain $HOME/android-ndk-r21/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64
    -Wl,--fix-cortex-a53-835769
    -Wl,--fix-cortex-a53-843419
    -no-canonical-prefixes
    -Wl,--gc-sections
    -Wl,--no-undefined
    -Wl,-z,nocopyreloc
    -Wl,-z,noexecstack
    -Wl,-z,relro
    -Wl,-z,now
    -Wl,--warn-shared-textrel
    -Wl,--fatal-warnings
    --sysroot=$HOME/android-ndk-r21/platforms/android-21/arch-arm64
    $PROJECT/obj/android/testapp-aarch64.o
    $FRAMEWORK/c/tables/tables.android-arm64.o
    $HOME/ldc.runtime.android-arm64/lib/libdruntime-ldc-debug.a
    $FRAMEWORK/c/zlib/libz.android-aarch64.a
    -lc
    -lm
    -ldl
    -llog
    -lgcc
    -landroid
    $FRAMEWORK/c/pcre-8.42/libpcre.android-aarch64.a
    $PROJECT/obj/android/res-aarch64/res.o

**Comment by MartinKrocek** [comment] 2020-03-07 16:02
I build ldc and ldc runtime from master, and now i have an error:

ld.bfd: _tlsstart: TLS definition in testapp-aarch64.o section .tdata mismatches non-TLS reference in ldc.runtime.android-arm64/lib/libdruntime-ldc-debug.a(sections_android.o)

file ldc/driver/codegenerator.cpp placed this symbol into ".tdata" segment
![image](https://user-images.githubusercontent.com/61880056/76146690-c2fe9500-60b6-11ea-99ce-824f379c8448.png)

**Comment by kinke** [comment] 2020-03-07 16:08
Do you use an official prebuilt package from GitHub? You need our forked LLVM for Android TLS emulation.

**Comment by kinke** [comment] 2020-03-07 16:14
(You can also use a prebuilt CI package: https://github.com/ldc-developers/ldc/releases/tag/CI.)

**Comment by MartinKrocek** [comment] 2020-03-07 20:24
>You need our forked LLVM for Android TLS emulation.

I rebuilded last version LDC from git with this LLVM.

-mtriple=armv7-none-linux-androideabi - **ok**
-mtriple=aarch64-none-linux-android - **now ok** thank you, it works!
-mtriple=i686-none-linux-android - still failed with SIGSEGV
-mtriple=x86_64-none-linux-android - still failed with SIGSEGV

call stack for x86_64:
```
_D2gc4impl12conservativeQw3Gcx12collectRootsMFNbNlPvQcZv+102
_D2gc4impl12conservativeQw3Gcx15collectAllRootsMFNbbZ14__foreachbody3MFNbKS4coreQDa11gcinterface5RangeZi+46
_D2rt4util9container5treap__T5TreapTS4core2gc11gcinterface5RangeZQBk7opApplyMFNbMDFNbKQByZiZ9__lambda2MFNbKxSQCuQCsQCsQCiZi+12
_D2rt4util9container5treap__T5TreapTS4core2gc11gcinterface5RangeZQBk13opApplyHelperFNbxPSQDjQDjQDhQDa__TQCxTQCuZQDf4NodeMDFNbKxSQDnQDlQDlQDbZiZi+103
_D2rt4util9container5treap__T5TreapTS4core2gc11gcinterface5RangeZQBk7opApplyMxFNbMDFNbKxSQCaQByQByQBoZiZi+31
_D2rt4util9container5treap__T5TreapTS4core2gc11gcinterface5RangeZQBk7opApplyMFNbMDFNbKQByZiZi+39
_D2gc4impl12conservativeQw3Gcx15collectAllRootsMFNbbZv+136
_D2gc4impl12conservativeQw3Gcx12markParallelMFNbbZv+117
_D2gc4impl12conservativeQw3Gcx11fullcollectMFNbbZm+352
_D2gc4impl12conservativeQw3Gcx10smallAllocMFNbmKmkxC8TypeInfoZPv+632
_D2gc4impl12conservativeQw3Gcx5allocMFNbmKmkxC8TypeInfoZPv+60
_D2gc4impl12conservativeQw14ConservativeGC12mallocNoSyncMFNbmkKmxC8TypeInfoZPv+76
_D2gc4impl12conservativeQw14ConservativeGC__T9runLockedS_DQCeQCeQCcQCnQBs12mallocNoSyncMFNbmkKmxC8TypeInfoZPvS_DQEgQEgQEeQEp10mallocTimelS_DQFiQFiQFgQFr10numMallocslTmTkTmTxQCzZQFcMFNbKmKkKmKxQDsZQDl+69
_D2gc4impl12conservativeQw14ConservativeGC6qallocMFNbmkxC8TypeInfoZS4core6memory8BlkInfo_+145
_DThn16_2gc4impl12conservativeQw14ConservativeGC6qallocMFNbmkxC8TypeInfoZS4core6memory8BlkInfo_+26
gc_qalloc+76
_D2gc4impl5protoQo7ProtoGC6qallocMFNbmkxC8TypeInfoZS4core6memory8BlkInfo_+58
_DThn16_2gc4impl5protoQo7ProtoGC6qallocMFNbmkxC8TypeInfoZS4core6memory8BlkInfo_+26
gc_qalloc+76
_D4core6memory2GC6qallocFNaNbmkxC8TypeInfoZSQBqQBo8BlkInfo_+41
_D2rt8lifetime12__arrayAllocFNaNbmxC8TypeInfoxQlZS4core6memory8BlkInfo_+365
_d_newarrayU+208
_D6object__T4_dupTaTyaZQlFNaNbAaZAya+31
_D6object__T11_trustedDupTaTyaZQtFNaNbNeAaZAya+28
_D6object__T4idupTaZQiFNaNbNdNfAaZAya+28

here i'm trying to call "idup"

_D9framework2os6Config25_sharedStaticCtor_L160_C1FZv+38
_D2rt5minfo__T14runModuleFuncsSQBdQBd11ModuleGroup8runCtorsMFZ9__lambda2ZQChMFAxPyS6object10ModuleInfoZv+88
_D2rt5minfo11ModuleGroup8runCtorsMFZv+60
_D2rt5minfo13rt_moduleCtorUZ14__foreachbody1MFKSQBu16sections_android12SectionGroupZi+48
_D2rt16sections_android12SectionGroup7opApplyFMDFKSQBxQBxQBiZiZi+35
rt_moduleCtor+19
rt_init+91
_android_app_thread+220
__pthread_start(void*)+46
__start_thread+11
__bionic_clone+53

```

**Comment by kinke** [comment] 2020-03-07 22:26
Glad it works for AArch64 now at least. - Looks like the GC is scanning an invalid range, probably returned in rt/sections_android.d's `initSections()` (output of `&{_tlsstart,_tlsend,__bss_end__}` and comparison against ARM output could be interesting, as well as the failing address). Adding `-v` to the clang linker cmdliner could also be interesting for the underlying ld cmdline, to see if it does something different for x86 architectures.

**Comment by MartinKrocek** [comment] 2020-03-08 07:56
>Adding -v to the clang linker cmdliner could also be interesting for the underlying ld cmdline
arm/aarch64 linker has only 2 aaditional flags -EL and -X

>rt/sections_android.d's initSections() (output of &{_tlsstart,_tlsend,__bss_end__}
The main difference x86 has no __bss_end__
![image](https://user-images.githubusercontent.com/61880056/76158846-15ce6000-613c-11ea-88cb-33efea366216.png)


![image](https://user-images.githubusercontent.com/61880056/76158771-3a760800-613b-11ea-87e7-6cdbed7b43c1.png)


![image](https://user-images.githubusercontent.com/61880056/76158794-8163fd80-613b-11ea-86c1-3ecae62a1a9e.png)

**Comment by kinke** [comment] 2020-03-08 10:08
Looks promising. - It's probably time to revamp `sections_android.d` and getting rid of the dependence on these magic symbols. IIRC, `__bss_end__` (for ARM archs) is the reason we need `ld.bfd` for Android (and e.g. `ld.gold` doesn't work). And `_tls{start,end}` are emitted manually by the compiler in the object file containing D main, and that's why it needs to be the first object in the linker cmdline. Joakim wanted to get rid of this and parse the ELF headers instead, but he was waiting for https://github.com/dlang/druntime/pull/2330, which was recently merged (after 2+ years) and is already available in our 2.091 branch (https://github.com/ldc-developers/druntime/tree/ldc-merge-2.091/src/core/internal/elf, see #3333).

**Comment by kinke** [comment] 2020-03-09 00:47
Could you please refetch master (now based on 2.091), rebuild and then test the following?
```D
import core.internal.elf.dl;
import core.internal.elf.io;
import core.stdc.stdio;
import core.sys.linux.elf;

version (Android)
{
    extern __gshared extern(C)
    {
        version (X86_Any)
        {
            size_t _end;
            alias __bss_end__ = _end;
        }
        else
        {
            size_t __bss_end__;
        }

        int _tlsstart;
        int _tlsend;
    }
}

import ldc.attributes;
@section("mySection") __gshared size_t myGlobal;

void main()
{
    version (Android)
    {
        printf("&_tlsstart:   %p\n", &_tlsstart);
        printf("&_tlsend:     %p\n", &_tlsend);
        printf("&__bss_end__: %p\n", &__bss_end__);
    }

    SharedObject object;

    __gshared int var;
    if (!SharedObject.findForAddress(&var, object))
        assert(0, "cannot find SharedObject");

    printf("ELF object base: %p\n", object.baseAddress);

    scanSegments(object);
    scanSections(object);

    myGlobal = 123; // don't strip
}

void scanSegments(const ref SharedObject object)
{
    foreach (ref phdr; object)
    {
        if (phdr.p_type == PT_LOAD && (phdr.p_flags & PF_W)) // writeable data segment
        {
            auto beg = object.baseAddress + (phdr.p_vaddr & ~(size_t.sizeof - 1));
            printf("data segment range: %p - %p\n", beg, beg + phdr.p_memsz);
        }
    }
}

void scanSections(const ref SharedObject object)
{
    ElfFile file;
    if (!ElfFile.open(object.name().ptr, file))
        assert(0, "cannot open ELF file");

    void checkSection(string name)
    {
        ElfSectionHeader sectionHeader;
        if (file.findSectionHeaderByName(name, sectionHeader))
        {
            auto beg = object.baseAddress + sectionHeader.shdr.sh_addr;
            printf("found section %.*s: %p - %p\n",
                cast(int) name.length, name.ptr, beg, beg + sectionHeader.shdr.sh_size);
        }
    }

    checkSection(".tdata");
    checkSection(".tbss");
    checkSection("mySection");
}
```

**Comment by MartinKrocek** [comment] 2020-03-09 06:42
-mtriple=i686-none-linux-android, shared .so, NativeActivity
```
initSections LDC mbeg = 0xa1b43a70, mend = 0xa1b44dcc
initSections LDC pbeg = 0xa1af2b74, pend = 0xb7757658
&_tlsstart:   0xa1af2a7c
&_tlsend:     0xa1af2b74
&__bss_end__: 0xb7757658
ELF object base: 0xa144b000
data segment range: 0xa1af2a7c - 0xa1b456d4
```

**Comment by kinke** [comment] 2020-03-09 13:42
Thx for testing, seems to work. Is that enough for you to attempt a `sections_android.d` PR? [Wrt. resorting to `/proc/self/maps`, it'd probably be nicer to check the address range to overcome potential issues wrt. duplicate .so names.]

**Comment by kinke** [comment] 2020-03-10 02:29
I've started refactoring stuff in https://github.com/ldc-developers/druntime/pull/178; I'll take a look at `sections_android.d` tomorrow if you don't beat me to it.

**Comment by kinke** [comment] 2020-03-10 21:33
I had a go at it; a test would be highly welcome.

**Comment by MartinKrocek** [comment] 2020-03-11 06:58
Please tell me how I can apply your changes?

I'm trying this
```
git fetch origin pull/3357/head:pr-3357
git checkout pr-3357
```
but sections_android.d not changed

**Comment by kinke** [comment] 2020-03-11 11:03
You don't need the LDC PR (which just removes `_tls{start,end}`), just the druntime one; that's a branch on our repo (not mine) and should thus be trivial to build. - You can also just download a prebuilt artifact produced by Azure Pipelines for #3357.

**Comment by MartinKrocek** [comment] 2020-03-11 12:03
-mtriple=i686-none-linux-android - ok, works without gc errors
Please wait about 60min, i will test for another android triples. Android emulator is not fast.

**Comment by kinke** [comment] 2020-03-11 12:47
I'm at work, so no hurry. ;) - Please specify which `safeAssert` fails (getting the file path via `/proc/<PID>/maps`?) and ideally try to fix it, as I can't test it (no Android dev env).

**Comment by MartinKrocek** [comment] 2020-03-11 13:28
ok, i try to find error, and make some tests

**Comment by MartinKrocek** [comment] 2020-03-11 14:50
I found bug!

In file runtime/druntime/src/core/sys/linux/link.d need to split version (ARM_Any) to ARM and AArch64, and define 32 and 64 bit types

Something like this:
![image](https://user-images.githubusercontent.com/61880056/76429615-19c6e000-63d1-11ea-8644-a3c40b212eea.png)

My application now works on AArch64

And the same need to split version (X86_Any) to X86 and X86_64

**Comment by kinke** [comment] 2020-03-11 16:10
Thx, I'll take care of that upstream. Could you please also test with `ld.gold` (I think that's the default, but just in case, use `-fuse-ld=gold` instead of `-fuse-ld=bfd` in clang cmdline)?

**Comment by MartinKrocek** [comment] 2020-03-11 16:31
No with "gold" not works
_D4core8internal5abortQgFNbNiNfMAyaMQekZv+184
_D2rt4util7utility10safeAssertFNbNiNfbMAyaMQekZv+92
_D2rt16sections_android12initSectionsFNbNiZ14__foreachbody1MFNbNiKxS4core3sys5linux3elf10Elf32_PhdrZi+212

Wait a minute, I try to make more tests, to find bug

**Comment by MartinKrocek** [comment] 2020-03-11 17:25
getStaticTLSRange() log
```
object.baseAddress = 0x91f49000
section : sh_addr = 0x0, sh_size = 0x0
section .note.android.ident: sh_addr = 0x134, sh_size = 0x98
section .dynsym: sh_addr = 0x1cc, sh_size = 0x394d0
section .dynstr: sh_addr = 0x3969c, sh_size = 0x13df23
section .gnu.hash: sh_addr = 0x1775c0, sh_size = 0x1a220
section .hash: sh_addr = 0x1917e0, sh_size = 0x16580
section .gnu.version: sh_addr = 0x1a7d60, sh_size = 0x729a
section .gnu.version_d: sh_addr = 0x1aeffc, sh_size = 0x1c
section .gnu.version_r: sh_addr = 0x1af018, sh_size = 0x60
section .rel.dyn: sh_addr = 0x1af078, sh_size = 0x1fe68
section .rel.plt: sh_addr = 0x1ceee0, sh_size = 0x112e0
section .plt: sh_addr = 0x1e01c0, sh_size = 0x19c64
section .text: sh_addr = 0x1f9e30, sh_size = 0x2ed1e0
section .ARM.exidx: sh_addr = 0x4e7010, sh_size = 0x7610
section .ARM.extab: sh_addr = 0x4ee620, sh_size = 0x8944
section .rodata: sh_addr = 0x4f6f80, sh_size = 0x125b79
section .data.rel.ro: sh_addr = 0x61e2b0, sh_size = 0x7a94
section .fini_array: sh_addr = 0x625d44, sh_size = 0x8
section .init_array: sh_addr = 0x625d4c, sh_size = 0xc
section .dynamic: sh_addr = 0x625d58, sh_size = 0x128
section .got: sh_addr = 0x625e80, sh_size = 0xa180
section .data: sh_addr = 0x630000, sh_size = 0x404f8
section __minfo: sh_addr = 0x6704f8, sh_size = 0x135c
section .bss: sh_addr = 0x671858, sh_size = 0x7a0
section .tbss: sh_addr = 0x671ff8, sh_size = 0x131
section .tbss: 0x925baff8 - 0x925bb129
section .comment: sh_addr = 0x0, sh_size = 0x101
section .debug_str: sh_addr = 0x0, sh_size = 0x18b1c7
section .debug_loc: sh_addr = 0x0, sh_size = 0x295a2
section .debug_abbrev: sh_addr = 0x0, sh_size = 0xb3d0
section .debug_info: sh_addr = 0x0, sh_size = 0xe1252
section .debug_ranges: sh_addr = 0x0, sh_size = 0x1a4f8
section .debug_macinfo: sh_addr = 0x0, sh_size = 0x6b
section .debug_pubnames: sh_addr = 0x0, sh_size = 0x645b4
section .debug_pubtypes: sh_addr = 0x0, sh_size = 0x184f6
section .debug_frame: sh_addr = 0x0, sh_size = 0x3fc90
section .debug_line: sh_addr = 0x0, sh_size = 0x95c96
section .debug_aranges: sh_addr = 0x0, sh_size = 0x380
section .note.gnu.gold-version: sh_addr = 0x0, sh_size = 0x1c
section .ARM.attributes: sh_addr = 0x0, sh_size = 0x38
section .symtab: sh_addr = 0x0, sh_size = 0x1019a0
section .strtab: sh_addr = 0x0, sh_size = 0x16a8c8
section .shstrtab: sh_addr = 0x0, sh_size = 0x1bb
```
data segment: 0x925672b0 - 0x925bb129
initSections() start = 0x925672b0, _staticTLSRange.ptr = 0x925baff8


Maybe this inforation can help find error

**Comment by kinke** [comment] 2020-03-11 17:35
Yeah, it's enough; here the data segment doesn't start with .tdata/.tbss (.tdata doesn't exist here, and .tbss is simply quite a bit further up than expected). The Android linker scripts probably diverge; no problem, just a bit more work.

**Comment by kinke** [comment] 2020-03-11 22:15
Okay, please retry one more time. Ideally, also with some *non-zero-initialized* TLS variable, so that there should be a `.tdata` section too - there's an assumption that both .tdata/.tbss are contiguous, which I hope also holds for gold.

**Comment by MartinKrocek** [comment] 2020-03-12 09:06
I tested your changes for arm, aarch64, x86 and x86_64, each for both linkers ld.bfd and ld.gold.
All targets works. Thank you.

But I have warnings (notices) R_ARM_TLS_LDO32 only on arm target (-mtriple=armv7-none-linux-androideabi) with linker ld.bfd. If I link application with ld.gold I have no this warnings. And if I link for other mtriples for both linkers I also have no this warnings.
```
libdruntime-ldc-debug.a(exception.o)(.debug_info+0x4f): R_ARM_TLS_LDO32 used with non-TLS symbol _D4core9exception6_storeG128v

libdruntime-ldc-debug.a(fiber.o)(.debug_info+0x32): R_ARM_TLS_LDO32 used with non-TLS symbol _D4core6thread5fiber5Fiber7sm_thisCQBhQBfQBbQy

libdruntime-ldc-debug.a(osthread.o)(.debug_info+0x62): R_ARM_TLS_LDO32 used with non-TLS symbol _D4core6thread8osthread11swapContextFNbNiPvZ5whichi

libdruntime-ldc-debug.a(osthread.o)(.debug_info+0xde8): R_ARM_TLS_LDO32 used with non-TLS symbol _D4core6thread8osthread6Thread7sm_thisCQBlQBjQBfQz

libdruntime-ldc-debug.a(deh_win64_posix.o)(.debug_info+0x38): R_ARM_TLS_LDO32 used with non-TLS symbol _D2rt15deh_win64_posix10__inflightPSQBiQBi8InFlight

libdruntime-ldc-debug.a(dwarfeh.o)(.debug_info+0x32): R_ARM_TLS_LDO32 used with non-TLS symbol _D2rt7dwarfeh15ExceptionHeader5stackPSQBkQBkQBf

libdruntime-ldc-debug.a(dwarfeh.o)(.debug_info+0x1f1): R_ARM_TLS_LDO32 used with non-TLS symbol _D2rt7dwarfeh15ExceptionHeader9ehstorageSQBnQBnQBi

libdruntime-ldc-debug.a(lifetime.o)(.debug_info+0x63): R_ARM_TLS_LDO32 used with non-TLS symbol _D2rt8lifetime18__blkcache_storagePS4core6memory8BlkInfo_

libdruntime-ldc-debug.a(lifetime.o)(.debug_info+0x7a): R_ARM_TLS_LDO32 used with non-TLS symbol _D2rt8lifetime12__nextBlkIdxi

libdruntime-ldc-debug.a(profilegc.o)(.debug_info+0x38): R_ARM_TLS_LDO32 used with non-TLS symbol _D2rt9profilegc6bufferAa

libdruntime-ldc-debug.a(profilegc.o)(.debug_info+0x4e): R_ARM_TLS_LDO32 used with non-TLS symbol _D2rt9profilegc9newCountsSQy4util9container7hashtab__T7HashTabTAxaTSQCoQCo5EntryZQBb

libdruntime-ldc-debug.a(gc.o)(.debug_info+0x1c7): R_ARM_TLS_LDO32 used with non-TLS symbol _D2gc4impl12conservativeQw14bytesAllocatedm

libdruntime-ldc-debug.a(gc.o)(.debug_info+0x59eb): R_ARM_TLS_LDO32 used with non-TLS symbol _D2gc4impl12conservativeQw14ConservativeGC12_inFinalizerb
```

**Comment by kinke** [comment] 2020-03-12 09:36
Excellent, thx for testing. The debuginfo warnings are probably valid and caused by the custom TLS emulation in our LLVM fork (replacing access to TLS vars by function calls...).

**Closed** 2020-03-16 12:34 UTC
