### ISSUE TITLE
Incorrect codegen for `ror(v,8) == v`

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#4753] opened 2024-09-14 22:14 UTC
Works for LDC 1.37 (LLVM 17), but is broken for 1.38 (LLVM 18)
Testcase:
```d
import core.bitop;

pragma(inline, false) // with inlining on, the bug does not show up
bool allEqual(const size_t v)
{
    return ror(v,8) == v;
} 

void main() {
    assert(!allEqual(0x8888_8818_8888_8888));
    assert(!allEqual(0x8888_8888_8881_8888));
}
```
https://godbolt.org/z/hG1sc6Y14

Note the wrong machine codegen of `allEqual`:
```asm
bool example.allEqual(const(ulong)):
        movzx   eax, dil ; saves the first 8 bits of argument
        shr     rdi, 56  ; discards the first 56 bits of argument
        cmp     rax, rdi ; compares the remaining 8 bits of argument with the saved 8 LSBs ???
        sete    al
        ret
```

first reported here: https://forum.dlang.org/post/djoqaiskwnxtzzjdqrdy@forum.dlang.org

**Comment by JohanEngelen** [comment] 2024-09-14 22:19
Our optimized LLVM IR is identical for 1.37 and 1.38, so looks like an LLVM codegen bug.
https://godbolt.org/z/Gnj5EYxMW

**Comment by dnadlinger** [comment] 2024-09-14 23:04
Yes, looks like an LLVM codegen bug indeed: https://github.com/llvm/llvm-project/issues/108722.

**Comment by kinke** [comment] 2024-09-16 12:02
Thx for digging & filing guys, let's close this then. LLVM 18 won't get the regression fix.

**Closed by kinke** 2024-09-16 12:02 UTC
Labels: A-wrong-code

**Comment by dnadlinger** [comment] 2024-09-16 12:48
I really don't understand LLVM's release model here, though. LLVM 19 isn't even out yet, and this is potentially quite a serious codegen regression in run-of-the-mill integer code…
