### ISSUE TITLE
Recursive main call causes a segfault in the compiler.

### ISSUE THREAD

**Issue by gimbles** [ldc-developers/ldc#4412] opened 2023-05-27 16:54 UTC
![image](https://github.com/ldc-developers/ldc/assets/93856041/c683872d-6d46-4974-8d65-9978d82feea8)

```d
int main() {
    main();
}
```

This segfaults ldc2 somehow?

**Comment by kinke** [comment] 2023-05-30 10:48
This is a duplicate of #2777; see https://github.com/ldc-developers/ldc/issues/2777#issuecomment-405370916 for an explanation (=> actual signature is `int _Dmain(string[] args)`; this magic isn't handled when calling it manually).

**Closed by kinke** 2023-05-30 10:48 UTC
