### ISSUE TITLE
Crash when calling main()

### ISSUE THREAD

**Issue by bbonf** [ldc-developers/ldc#3992] opened 2022-06-02 19:28 UTC
Hey,

ldc crashes for me when trying to compile the following (nonsensical) d code:
```
void main() {}

void foo() {
  main();
}
```

The crash log:
```
 #0 0x00007f9dbcc22fda (/usr/lib/libLLVM-13.so+0xb97fda)
 #1 0x00007f9dbcc2065f llvm::sys::RunSignalHandlers() (/usr/lib/libLLVM-13.so+0xb9565f)
 #2 0x00007f9dbcc207ad (/usr/lib/libLLVM-13.so+0xb957ad)
 #3 0x00007f9dbbb7e8e0 (/usr/lib/libc.so.6+0x3e8e0)
 #4 0x000055f9e7b25654 DtoCallFunction(Loc const&, Type*, DValue*, Array<Expression*>*, llvm::Value*) (/usr/bin/ldc2+0x90c654)
 #5 0x000055f9e7b351a4 (/usr/bin/ldc2+0x91c1a4)
 #6 0x000055f9e7b35403 (/usr/bin/ldc2+0x91c403)
 #7 0x000055f9e7b2a9f9 toElemDtor(Expression*) (/usr/bin/ldc2+0x9119f9)
 #8 0x000055f9e7b13b6a (/usr/bin/ldc2+0x8fab6a)
 #9 0x000055f9e7b13189 (/usr/bin/ldc2+0x8fa189)
#10 0x000055f9e7b12a4f Statement_toIR(Statement*, IRState*) (/usr/bin/ldc2+0x8f9a4f)
#11 0x000055f9e7aca701 DtoDefineFunction(FuncDeclaration*, bool) (/usr/bin/ldc2+0x8b1701)
#12 0x000055f9e7b9c316 Declaration_codegen(Dsymbol*) (/usr/bin/ldc2+0x983316)
#13 0x000055f9e7ae182a codegenModule(IRState*, Module*) (/usr/bin/ldc2+0x8c882a)
#14 0x000055f9e7baff2c ldc::CodeGenerator::emit(Module*) (/usr/bin/ldc2+0x996f2c)
#15 0x000055f9e7b7de83 codegenModules(Array<Module*>&) (/usr/bin/ldc2+0x964e83)
#16 0x000055f9e7809d50 mars_mainBody(Param&, Array<char const*>&, Array<char const*>&) (/usr/bin/ldc2+0x5f0d50)
#17 0x000055f9e7b80e88 cppmain() (/usr/bin/ldc2+0x967e88)
#18 0x000055f9e7d430ac _D2rt6dmain212_d_run_main2UAAamPUQgZiZ6runAllMFZv (/usr/bin/ldc2+0xb2a0ac)
#19 0x000055f9e7d42ec5 _d_run_main2 (/usr/bin/ldc2+0xb29ec5)
#20 0x000055f9e7d42d1e _d_run_main (/usr/bin/ldc2+0xb29d1e)
#21 0x000055f9e7632dc6 main (/usr/bin/ldc2+0x419dc6)
#22 0x00007f9dbbb69290 (/usr/lib/libc.so.6+0x29290)
#23 0x00007f9dbbb6934a __libc_start_main (/usr/lib/libc.so.6+0x2934a)
#24 0x000055f9e7634f85 _start (/usr/bin/ldc2+0x41bf85)
```

**Comment by kinke** [comment] 2022-06-02 19:49
Hi, this is a duplicate of https://github.com/ldc-developers/ldc/issues/2777 and https://github.com/ldc-developers/ldc/issues/2151. `main` is special and gets its signatures fixed up (for both `extern(D)` and `extern(C)`).

**Closed by kinke** 2022-06-02 19:49 UTC
