### ISSUE TITLE
-L--export-dynamic causes missing symbol hashOf with two libraries

### ISSUE THREAD

**Issue by FeepingCreature** [ldc-developers/ldc#3098] opened 2019-06-27 09:27 UTC
Consider the following setup:

Start with a file `lib_a.d` defining some logic on a struct:

```
struct Test(T) {
    T member;

    size_t toHash() const {
        return hashOf(member);
    }
}

enum duppable(T) = is(typeof(T.init.dup));

enum test = duppable!(Test!(void delegate())[]);
```

Link this into library `lib_a.a`: `$ ldc -lib lib_a.d -oflib_a.a`.

Create two more files, `lib_b1.d` and `lib_b2.d`:

lib_b1.d:
```
static this() { }
```

lib_b2.d:
```
import lib_a;

void foo() {
    cast(void) (void delegate()).init;
}
```

Link this into library `lib_b.a`: `$ ldc -lib lib_b1.d lib_b2.d -oflib_b.a`.

Now create a `main.d` file:

```
import lib_b1;
void main() { }
```

And finally, build it into a binary with the libraries and the linker flag `--export-dynamic`: `$ ldc main.d -L-L. -L-l_a -L-l_b -L--export-dynamic -of=test`.

Expected: success

Actual: `./lib_b.a(lib_b1.o):lib_b1.d:function _D5lib_a__T4TestTDFZvZQl6toHashMxFNaNbNiNfZm: Fehler: undefined reference to '_D4core8internal4hash__T6hashOfTDFZvZQnFNaNbNiNeMxDFZvmZm'`

Have "fun"!

**Comment by FeepingCreature** [comment] 2019-06-27 10:50
Looks like when mangling the `hashOf` ldc once uses the same type instance as a previous type, and once a different-but-equal instance. For some reason.

**Comment by FeepingCreature** [comment] 2019-06-27 15:28
Hm, having a hard time making progress on this.

In DMD, the relevant `hashOf` is mangled as `_D4core8internal4hash__T6hashOfTDFZvZQnFNaNbNiNeMxD**FZv**mZm` in druntime, in LDC as `_D4core8internal4hash__T6hashOfTDFZvZQnFNaNbNiNeMxD**Qs**mZm` (referencing the earlier `FZv`).

**Comment by kinke** [comment] 2019-06-27 19:41
I can reproduce this on Win64; somewhat reduced:
```D
// a.d
struct Test(T) {
    T member;

    size_t toHash() const {
        return hashOf(member);
    }
}

enum duppable(T) = is(typeof(T.init.dup));

enum test = duppable!(Test!(void delegate())[]);
```

```D
// b.d
import a;

void main()
{
    cast(void) (void delegate()).init;
}
```

```
> ldc2 -c a.d
> ldc2 -c b.d
> ldc2 a.obj b.obj
b.obj : error LNK2019: unresolved external symbol _D4core8internal4hash__T6hashOfTDFZvZQnFNaNbNiNeMxDFZvmZm referenced in function _D1a__T4TestTDFZvZQl6toHashMxFNaNbNiNfZm
```

Separate compilation is required to codegen the TypeInfos, `Test!(...).toHash()` etc. into both object files (clearly suboptimal, especially since it's instantiated a) in a speculative context and b) just in module `a`, but oh well). druntime's `hashOf()` template is emitted into `a.obj`, mangled with the backref (`Qs`); in `b.obj`, it's just declared as external (most likely due to template culling) with the mismatching non-backref mangling:

```
> dumpbin /symbols a.obj
00D 00000000 SECT5  notype ()    External     | _D4core8internal4hash__T6hashOfTDFZvZQnFNaNbNiNeMxDQsmZm
> dumpbin /symbols b.obj
02F 00000000 UNDEF  notype       External     | _D4core8internal4hash__T6hashOfTDFZvZQnFNaNbNiNeMxDFZvmZm
```

**This is also the case for DMD** (2.086.0):
```
> dumpbin /symbols a.obj
03B 00000000 SECTE  notype ()    External     | _D4core8internal4hash__T6hashOfTDFZvZQnFNaNbNiNeMxDQsmZm
> dumpbin /symbols b.obj
034 00000000 UNDEF  notype ()    External     | _D4core8internal4hash__T6hashOfTDFZvZQnFNaNbNiNeMxDFZvmZm
```

I guess DMD just gets lucky, e.g., by the linker picking `_D1a__T4TestTDFZvZQl6toHashMxFNaNbNiNfZm` from `a.obj` instead of `b.obj`.

**Comment by rainers** [comment] 2019-06-27 22:01
I suspect that a `Type.merge` call is missing for some instance of FZv, i.e. `void function()`. It is a vital condition for equal types to have the same pointer.

**Comment by kinke** [comment] 2019-06-27 22:14
Sounds good.

**Comment by dukc** [comment] 2019-07-04 16:13
I'm currently blocked from updating my spasm application from 1.14 to 1.16, probably because of this. Any workarouds?

**Comment by kinke** [comment] 2019-07-04 16:24
I don't think that's related at all, it's a simple non-templated symbol in druntime and as such shouldn't be referenced from betterC code.

**Comment by dukc** [comment] 2019-07-04 16:38
> 
> 
> I don't think that's related at all, it's a simple non-templated symbol in druntime and as such shouldn't be referenced from betterC code.

But even if it was intended to be referred from `-betterC`, shouldn't the spasm definition override the DRuntime one, as it did with 1.14.0-beta1y? The ldc DRuntime definition of `core.internal.string.TempStringNoAlloc.get` has not changed.

**Comment by kinke** [comment] 2019-07-04 18:24
I'm not familiar with spasm. The mangling of that symbol hasn't changed from v1.14, and contains no backrefs, so this issue is definitely not related, and further discussions be in the spasm repo.

**Comment by dukc** [comment] 2019-07-05 10:46
> 
> 
> I'm not familiar with spasm. The mangling of that symbol hasn't changed from v1.14, and contains no backrefs, so this issue is definitely not related, and further discussions should be in the spasm repo.

Neither did spasm change, when I updated the compiler, and the erroring started. It has it's own definition of `TempStringNoAlloc.get`. What has changed, is a change you made yourself: #3072. You're probably aware of this, but just in case: spasm applications compile to webassembly. Thus, the compiler update made my application to start using `--export-dynamic`, and my error is similar (member function name mangled from a wrong module). This in my opinion tells that my issue is almost certainly the same as here.

**Comment by kinke** [comment] 2019-07-05 14:16
> This in my opinion tells that my issue is almost certainly the same as here.

It isn't; I've just verified that this issue here also applies to LDC 1.14.

**Comment by dukc** [comment] 2019-07-05 20:14
> Are you using `-fvisibility=hidden` and selectively `export`ing what you need?
Yes

**Comment by kinke** [comment] 2021-01-29 21:43
Should be fixed by https://github.com/dlang/dmd/pull/12166.

**Comment by kinke** [comment] 2021-02-09 03:49
That PR above has landed in DMD stable and LDC master.

**Closed by kinke** 2021-02-09 03:49 UTC
